name = "codetic"
defaultTargets = ["Codetic"]
testDriver = "CodeticTest"
precompileModules = false # We would like to turn this on, but it breaks the Mathlib cache.
platformIndependent = true

leanOptions = {experimental.module = true}

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "v4.25.0"

[[lean_lib]]
name = "Codetic"

[[lean_lib]]
name = "CodeticTest"
globs = ["CodeticTest.+"]
leanOptions = {linter.unusedVariables = false}
