/-
Copyright (c) 2021 Jannis Limperg. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jannis Limperg
-/
module

public import Lean.Data.Options

public section

open Lean

namespace Codetic

initialize Check.all : Lean.Option Bool ←
  Option.register `codetic.check.all
    { defValue := false
      descr := "(codetic) Enable all runtime checks. Individual checks can still be disabled."
      group := "tactic" }

structure Check where
  toOption : Lean.Option Bool

namespace Check

def get (opts : Options) (opt : Check) : Bool :=
  if let some val := opt.toOption.get? opts then
    val
  else
    Check.all.get opts

def isEnabled [Monad m] [MonadOptions m] (opt : Check) : m Bool :=
  return opt.get (← getOptions)

def name (opt : Check) : Name :=
  opt.toOption.name

end Check

-- Inspired by `Lean.Data.Options`.
local macro "register_codetic_check_option" optName:ident descr:str : command =>
  `(initialize option : Lean.Option Bool ←
      Lean.Option.register $(quote $ `codetic.check ++ optName.getId)
        { defValue := false, descr := $descr, group := "tactic" }

    def $(mkIdent $ `Check ++ optName.getId) : Codetic.Check := ⟨option⟩)

register_codetic_check_option proofReconstruction
    "(codetic) Typecheck partial proof terms during proof reconstruction."

register_codetic_check_option tree
    "(codetic) Check search tree invariants after every iteration of the search loop. Quite expensive."

register_codetic_check_option rules
    "(codetic) Check that information reported by rules is correct."

register_codetic_check_option script
    "(codetic) Check that the tactic script generated by Codetic proves the goal. When this check is active, Codetic generates a tactic script even if the user did not request one."

register_codetic_check_option script.steps
    "(codetic) Check each step of the tactic script generated by Codetic. When this check is active, Codetic generates a tactic script even if the user did not request one."

end Codetic
