/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: ade95481-31b0-45d7-8bf1-994bc8e48f13

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
This module implements a function `singleDigitPrimeFactor` that returns the smallest prime factor of a natural number `n` that is less than 10 (i.e., 2, 3, 5, or 7), or 0 if no such factor exists. It also defines pre- and post-conditions and proves that the implementation satisfies the specification.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

@[reducible, simp]
def singleDigitPrimeFactor_precond (n : Nat) : Prop :=
  True

def singleDigitPrimeFactor (n : Nat) (h_precond : singleDigitPrimeFactor_precond (n)) : Nat :=
  if n == 0 then 0
  else if n % 2 == 0 then 2
  else if n % 3 == 0 then 3
  else if n % 5 == 0 then 5
  else if n % 7 == 0 then 7
  else 0

@[reducible, simp]
def singleDigitPrimeFactor_postcond (n : Nat) (result: Nat) (h_precond : singleDigitPrimeFactor_precond (n)) : Prop :=
  result ∈ [0, 2, 3, 5, 7] ∧
  (result = 0 → (n = 0 ∨ [2, 3, 5, 7].all (n % · ≠ 0))) ∧
  (result ≠ 0 → n ≠ 0 ∧ n % result == 0 ∧ (List.range result).all (fun x => x ∈ [2, 3, 5, 7] → n % x ≠ 0))

theorem singleDigitPrimeFactor_spec_satisfied (n: Nat) (h_precond : singleDigitPrimeFactor_precond (n)) :
    singleDigitPrimeFactor_postcond (n) (singleDigitPrimeFactor (n) h_precond) h_precond := by
  -- We'll use the fact that the function `singleDigitPrimeFactor` returns the smallest prime factor of `n` or 0 if `n` has no single-digit prime factors.
  cases' n with n <;> simp +decide [ singleDigitPrimeFactor ] at *;
  -- By definition of `singleDigitPrimeFactor`, we know that if `n` is not zero, then `singleDigitPrimeFactor n` returns the smallest prime factor of `n` or 0 if `n` has no single-digit prime factors.
  by_cases h2 : (n + 1) % 2 = 0 ∨ (n + 1) % 3 = 0 ∨ (n + 1) % 5 = 0 ∨ (n + 1) % 7 = 0;
  · rcases h2 with ( h | h | h | h ) <;> simp_all +decide;
    · grind;
    · grind;
    · grind;
    · grind;
  · grind
