/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: e3b8f2ae-d56a-4371-b427-ddbf8edc8807

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
We defined the function `minOperations` which calculates the minimum number of operations to collect all integers from 1 to k from the end of a list `nums`. We also defined the precondition `minOperations_precond` (requiring `nums` to contain all integers from 1 to k) and the postcondition `minOperations_postcond` (asserting correctness and minimality). Finally, we proved `minOperations_spec_satisfied`, showing that `minOperations` satisfies the postcondition when the precondition holds.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

@[reducible, simp]
def minOperations_precond (nums : List Nat) (k : Nat) : Prop :=
  let target_nums := (List.range k).map (· + 1)
  target_nums.all (fun n => List.elem n nums)

def minOperations (nums : List Nat) (k : Nat) (h_precond : minOperations_precond (nums) (k)) : Nat :=
  if k == 0 then 0 else
  let rec loop (remaining : List Nat) (collected : List Nat) (collected_count : Nat) (ops : Nat) : Nat :=
    match remaining with
    | [] => ops
    | head :: tail =>
      let ops' := ops + 1
      if head > 0 && head <= k && !(List.elem head collected) then
          let collected' := head :: collected
          let collected_count' := collected_count + 1
          if collected_count' == k then
            ops'
          else
            loop tail collected' collected_count' ops'
      else
        loop tail collected collected_count ops'
  loop nums.reverse [] 0 0

@[reducible, simp]
def minOperations_postcond (nums : List Nat) (k : Nat) (result: Nat) (h_precond : minOperations_precond (nums) (k)) : Prop :=
  let processed := (nums.reverse).take result
  let target_nums := (List.range k).map (· + 1)
  let collected_all := target_nums.all (fun n => List.elem n processed)
  let is_minimal :=
    if result > 0 then
      let processed_minus_one := (nums.reverse).take (result - 1)
      ¬ (target_nums.all (fun n => List.elem n processed_minus_one))
    else
      k == 0
  collected_all ∧ is_minimal

def helper_loop (k : Nat) (remaining : List Nat) (collected : List Nat) (collected_count : Nat) (ops : Nat) : Nat :=
  match remaining with
  | [] => ops
  | head :: tail =>
    let ops' := ops + 1
    if head > 0 && head <= k && !(List.elem head collected) then
        let collected' := head :: collected
        let collected_count' := collected_count + 1
        if collected_count' == k then
          ops'
        else
          helper_loop k tail collected' collected_count' ops'
    else
      helper_loop k tail collected collected_count ops'

theorem minOperations_eq_helper_loop (nums : List Nat) (k : Nat) (h : minOperations_precond nums k) :
  minOperations nums k h = if k == 0 then 0 else helper_loop k nums.reverse [] 0 0 := by
    -- By definition of `minOperations`, we know that it is equal to `helper_loop` when `k` is not zero.
    simp [minOperations];
    -- Since the loop function and helper_loop are defined with the same recursive structure and base case, they are equal.
    have h_loop_eq_helper : ∀ (remaining : List ℕ) (collected : List ℕ) (collected_count : ℕ) (ops : ℕ), minOperations.loop k remaining collected collected_count ops = helper_loop k remaining collected collected_count ops := by
      -- By induction on the remaining list, we can show that the two functions are equal.
      intros remaining collected collected_count ops
      induction' remaining with head tail ih generalizing collected collected_count ops;
      · rfl;
      · -- By definition of `minOperations.loop` and `helper_loop`, they are equal for the case when the remaining list is non-empty.
        simp [minOperations.loop, helper_loop, ih];
    -- Apply the equality of the loop function and helper_loop to conclude the proof.
    simp [h_loop_eq_helper]

theorem helper_loop_add_ops (k : Nat) (remaining : List Nat) (collected : List Nat) (count : Nat) (ops d : Nat) :
  helper_loop k remaining collected count (ops + d) = helper_loop k remaining collected count ops + d := by
    -- By induction on the remaining list, we can show that helper_loop is linear in the operations parameter.
    induction' remaining with head tail ih generalizing collected count ops d;
    · -- In the base case, when the remaining list is empty, the helper_loop function returns the ops parameter.
      simp [helper_loop];
    · simp_all +decide [ helper_loop ];
      split_ifs <;> ring

def TargetSatisfied (L : List Nat) (k : Nat) : Prop :=
  ((List.range k).map (· + 1)).all (fun n => List.elem n L)

theorem TargetSatisfied_mono {L1 L2 : List Nat} (k : Nat) (h : L1 ⊆ L2) :
  TargetSatisfied L1 k → TargetSatisfied L2 k := by
    -- If L1 satisfies the target condition, then every number from 1 to k is present in L1. Since L1 is a subset of L2, those numbers must also be in L2. Therefore, L2 must also satisfy the target condition.
    intro hL1
    simp [TargetSatisfied] at hL1 ⊢;
    -- Since $L1 \subseteq L2$, if $x + 1 \in L1$, then $x + 1 \in L2$.
    intros x hx
    apply h
    apply hL1 x hx

def HelperLoopPost (k : Nat) (L : List Nat) (collected : List Nat) (ops : Nat) (res : Nat) : Prop :=
  let taken := res - ops
  taken ≤ L.length ∧
  TargetSatisfied (collected ++ L.take taken) k ∧
  (taken > 0 → ¬ TargetSatisfied (collected ++ L.take (taken - 1)) k)

def LoopInvariant (k : Nat) (collected : List Nat) (count : Nat) : Prop :=
  collected.Nodup ∧
  (∀ x ∈ collected, x > 0 ∧ x ≤ k) ∧
  collected.length = count ∧
  count < k

def HelperLoopCorrect (k : Nat) (remaining : List Nat) (collected : List Nat) (ops : Nat) (res : Nat) : Prop :=
  let taken := res - ops
  taken ≤ remaining.length ∧
  (TargetSatisfied (collected ++ remaining.take taken) k ∨ taken = remaining.length) ∧
  (∀ t < taken, ¬ TargetSatisfied (collected ++ remaining.take t) k)

theorem TargetSatisfied_perm_cons (k : Nat) (head : Nat) (L : List Nat) :
  TargetSatisfied (head :: L) k ↔ TargetSatisfied (L ++ [head]) k := by
    -- By definition of `TargetSatisfied`, we know that if `head :: L` satisfies the target condition, then `L ++ [head]` also satisfies it, and vice versa.
    simp [TargetSatisfied];
    grind

theorem TargetSatisfied_skip (k : Nat) (c : List Nat) (h : Nat) (L : List Nat)
  (cond : (h > k ∨ h = 0) ∨ h ∈ c) :
  TargetSatisfied (c ++ h :: L) k ↔ TargetSatisfied (c ++ L) k := by
    -- Since h is not in c and either h > k or h = 0, adding h to the list doesn't introduce any new elements that are between 1 and k. Therefore, the target satisfaction for c ++ h :: L is the same as for c ++ L.
    have h_target_satisfaction : ∀ n ∈ List.range k, n + 1 ∈ c ++ h :: L ↔ n + 1 ∈ c ++ L := by
      grind;
    -- By definition of TargetSatisfied, we need to show that for all n in the range k, n + 1 is in c ++ h :: L if and only if it's in c ++ L.
    simp [TargetSatisfied, h_target_satisfaction];
    grind

theorem TargetSatisfied_congr (L1 L2 : List Nat) (k : Nat) (h : ∀ x, x ∈ L1 ↔ x ∈ L2) :
  TargetSatisfied L1 k ↔ TargetSatisfied L2 k := by
    -- Since L1 and L2 have the same elements, any element in the target set must be in both L1 and L2.
    simp [TargetSatisfied, h]

theorem TargetSatisfied_length_le (L : List Nat) (k : Nat) (h_nodup : L.Nodup) (h_len : L.length < k) :
  ¬ TargetSatisfied L k := by
    -- Since L has length less than k, there must be some element in the target set {1, 2, ..., k} that's not in L.
    have h_exists_not_in_L : ∃ x ∈ (List.range k).map (· + 1), x ∉ L := by
      -- Since L has length less than k, there must be some element in the target set {1, 2, ..., k} that's not in L. We can use the pigeonhole principle here.
      have h_exists_not_in_L : Finset.card (Finset.image (fun x => x + 1) (Finset.range k)) > Finset.card (L.toFinset) := by
        -- Since L has length less than k, the cardinality of L's finset is less than k.
        have h_card_L : L.toFinset.card ≤ L.length := by
          exact List.toFinset_card_le _;
        rw [ Finset.card_image_of_injective ] <;> norm_num [ Function.Injective ] ; linarith;
      contrapose! h_exists_not_in_L;
      exact Finset.card_le_card fun x hx => by aesop;
    unfold TargetSatisfied; aesop;

theorem TargetSatisfied_of_length_eq_k (L : List Nat) (k : Nat)
  (h_nodup : L.Nodup)
  (h_len : L.length = k)
  (h_range : ∀ x ∈ L, x > 0 ∧ x ≤ k) :
  TargetSatisfied L k := by
    -- Since L has exactly k elements and each element is between 1 and k, L must contain every number from 1 to k exactly once.
    have h_all : ∀ n ∈ (List.range k).map (· + 1), n ∈ L := by
      have h_all : L.toFinset = Finset.Icc 1 k := by
        -- Since $L$ has length $k$ and each element is between $1$ and $k$, the Finset of $L$ must contain exactly the elements $1, 2, \ldots, k$.
        have h_finset : L.toFinset ⊆ Finset.Icc 1 k := by
          exact fun x hx => Finset.mem_Icc.mpr <| h_range x <| List.mem_toFinset.mp hx;
        exact Finset.eq_of_subset_of_card_le h_finset ( by rw [ List.toFinset_card_of_nodup h_nodup ] ; aesop );
      simp_all +decide [ Finset.ext_iff ];
      exact fun a ha => Nat.succ_le_of_lt ha;
    unfold TargetSatisfied; aesop;

theorem TargetSatisfied_cons_swap (k : Nat) (h : Nat) (c t : List Nat) :
  TargetSatisfied (c ++ h :: t) k ↔ TargetSatisfied (h :: c ++ t) k := by
    -- By definition of `TargetSatisfied`, we know that if `h ∈ target_nums`, then `h` must be in the list.
    unfold TargetSatisfied; simp [List.mem_append, List.mem_cons];
    -- The two statements are equivalent because logical OR is commutative.
    simp [or_comm, or_assoc, or_left_comm]

theorem helper_loop_correctness (k : Nat) (remaining : List Nat) (collected : List Nat) (count : Nat) (ops : Nat)
  (hk : k > 0)
  (h_inv : LoopInvariant k collected count) :
  HelperLoopCorrect k remaining collected ops (helper_loop k remaining collected count ops) := by
    -- By definition of `helper_loop`, we know that it returns the correct result for the base case.
    have h_base : ∀ (k : Nat) (collected : List Nat) (count : Nat) (ops : Nat), count < k → HelperLoopCorrect k [] collected ops (helper_loop k [] collected count ops) := by
      -- In the base case, when the remaining list is empty, the helper_loop returns the current operations value.
      intros k collected count ops h_count
      simp [helper_loop];
      constructor <;> aesop;
    -- By induction on the length of the remaining list, we can show that the helper loop is correct.
    induction' remaining with head tail ih generalizing collected count ops;
    · exact h_base k collected count ops h_inv.2.2.2;
    · by_cases h_head : head > 0 ∧ head ≤ k ∧ !(List.elem head collected);
      · specialize ih (head :: collected) (count + 1) (ops + 1);
        simp_all +decide [ LoopInvariant ];
        by_cases h_count : count + 1 < k <;> simp_all +decide [ HelperLoopCorrect ];
        · rw [ show helper_loop k ( head :: tail ) collected count ops = helper_loop k tail ( head :: collected ) ( count + 1 ) ( ops + 1 ) from ?_ ];
          · simp_all +decide [ Nat.sub_sub, add_comm, add_left_comm, add_assoc ];
            rw [ show helper_loop k tail ( head :: collected ) ( count + 1 ) ( ops + 1 ) - ops = ( helper_loop k tail ( head :: collected ) ( count + 1 ) ( ops + 1 ) - ( ops + 1 ) ) + 1 from ?_ ];
            · simp_all +decide [ List.take, List.drop ];
              refine' ⟨ _, _ ⟩;
              · convert ih.2.1 using 1;
                convert TargetSatisfied_cons_swap k head collected ( List.take ( helper_loop k tail ( head :: collected ) ( count + 1 ) ( ops + 1 ) - ( ops + 1 ) ) tail ) using 1;
              · intro t ht; rcases t with ( _ | t ) <;> simp_all +decide [ List.take ] ;
                · intro h; have := h_inv.2.2.1; simp_all +decide [ TargetSatisfied ] ;
                  exact absurd ( List.toFinset_card_of_nodup h_inv.1 ▸ Finset.card_le_card ( show List.toFinset collected ⊇ Finset.Icc 1 k from fun x hx => by have := h ( x - 1 ) ( by linarith [ Finset.mem_Icc.mp hx, Nat.sub_add_cancel ( by linarith [ Finset.mem_Icc.mp hx ] : 1 ≤ x ) ] ) ; cases x <;> aesop ) ) ( by norm_num; linarith );
                · convert ih.2.2 t ht using 1;
                  convert TargetSatisfied_cons_swap k head collected ( List.take t tail ) using 1;
            · rw [ tsub_add_eq_add_tsub ];
              · rw [ Nat.add_sub_add_right ];
              · -- By definition of `helper_loop`, we know that it returns the correct result for the base case and the inductive step.
                have h_helper_loop : ∀ (k : Nat) (remaining : List Nat) (collected : List Nat) (count : Nat) (ops : Nat), count < k → ops ≤ helper_loop k remaining collected count ops := by
                  intros k remaining collected count ops h_count; induction' remaining with head tail ih generalizing collected count ops; simp_all +decide [ helper_loop ] ;
                  by_cases h_head : head > 0 ∧ head ≤ k ∧ !(List.elem head collected) <;> simp_all +decide [ helper_loop ];
                  · grind;
                  · grind;
                exact h_helper_loop _ _ _ _ _ h_count;
          · exact if_pos ( by aesop ) |> fun h => h.trans ( by aesop );
        · -- Since $k = count + 1$, we have $helper\_loop k (head :: tail) collected count ops = ops + 1$.
          have h_helper_loop_eq : helper_loop k (head :: tail) collected count ops = ops + 1 := by
            simp +decide [ *, helper_loop ];
            grind;
          -- Since $k = count + 1$, the collected list plus the head should satisfy the target.
          have h_target_satisfied : TargetSatisfied (collected ++ [head]) k := by
            have h_target_satisfied : collected.length + 1 = k := by
              grind;
            apply TargetSatisfied_of_length_eq_k;
            · grind;
            · simp +arith +decide [ h_target_satisfied ];
            · grind;
          -- Since $t < 1$, the only possible value for $t$ is $0$. Therefore, we need to show that the collected list plus the first $0$ elements of the tail doesn't satisfy the target.
          have h_t_zero : ∀ t < 1, ¬TargetSatisfied (collected ++ List.take t (head :: tail)) k := by
            simp_all +decide [ TargetSatisfied ];
            exact ⟨ head - 1, by omega, by cases head <;> aesop ⟩;
          simp_all +decide [ add_comm, add_left_comm, add_assoc ];
      · simp_all +decide [ HelperLoopCorrect ];
        rw [ show helper_loop k ( head :: tail ) collected count ops = helper_loop k tail collected count ( ops + 1 ) from ?_ ];
        · specialize ih collected count ( ops + 1 ) h_inv ; simp_all +decide [ add_comm, add_left_comm, add_assoc ] ;
          constructor;
          · rw [ show helper_loop k tail collected count ( ops + 1 ) - ops = ( helper_loop k tail collected count ( ops + 1 ) - ( ops + 1 ) ) + 1 from ?_ ];
            · cases ih.2.1 <;> simp_all +decide [ List.take ];
              exact Or.inl ( TargetSatisfied_mono _ ( by aesop_cat ) ‹TargetSatisfied ( collected ++ List.take ( helper_loop k tail collected count ( ops + 1 ) - ( ops + 1 ) ) tail ) k› );
            · rw [ tsub_add_eq_add_tsub ];
              · rw [ Nat.add_sub_add_right ];
              · -- By definition of `helper_loop`, we know that it returns the correct result for the base case and the inductive step.
                have h_helper_loop_ge : ∀ (k : Nat) (remaining : List Nat) (collected : List Nat) (count : Nat) (ops : Nat), count < k → ops ≤ helper_loop k remaining collected count ops := by
                  intros k remaining collected count ops h_count_lt_k
                  induction' remaining with head tail ih generalizing collected count ops;
                  · exact?;
                  · by_cases h_head : head > 0 ∧ head ≤ k ∧ ¬ List.elem head collected <;> simp_all +decide [ helper_loop ];
                    · grind;
                    · grind;
                exact h_helper_loop_ge _ _ _ _ _ ( h_inv.2.2.2 );
          · intro t ht; specialize ih; rcases t with ( _ | t ) <;> simp_all +decide [ Nat.succ_sub ] ;
            · -- Since `count < k`, the collected list cannot contain all elements from 1 to k.
              have h_count_lt_k : count < k := by
                exact h_inv.2.2.2;
              have h_count_lt_k : collected.length < k := by
                linarith [ h_inv.2.2.1 ];
              apply TargetSatisfied_length_le;
              · exact h_inv.1;
              · linarith;
            · convert ih.2.2 t ( by omega ) using 1;
              by_cases h : 0 < head <;> by_cases h' : head ≤ k <;> simp_all +decide [ TargetSatisfied ];
              · grind;
              · grind;
        · exact if_neg ( by aesop )

theorem minOperations_spec_satisfied (nums: List Nat) (k: Nat) (h_precond : minOperations_precond (nums) (k)) :
    minOperations_postcond (nums) (k) (minOperations (nums) (k) h_precond) h_precond := by
      -- By definition of `minOperations`, we know that it satisfies the postcondition when `k` is not zero. We'll use the fact that `minOperations` is defined recursively to show this.
      have h_minOperations_postcond : ∀ (k : Nat) (remaining : List Nat) (collected : List Nat) (count ops : Nat), k > 0 → LoopInvariant k collected count → HelperLoopCorrect k remaining collected ops (helper_loop k remaining collected count ops) := by
        exact?;
      by_cases hk : k > 0 <;> simp_all +decide [ minOperations_eq_helper_loop ];
      -- Apply the helper_loop_correctness theorem with the given parameters.
      have h_helperLoopCorrect : HelperLoopCorrect k (nums.reverse) [] 0 (helper_loop k (nums.reverse) [] 0 0) := by
        exact h_minOperations_postcond k nums.reverse [] 0 0 hk ⟨ by simp +decide, by simp +decide, by simp +decide, hk ⟩;
      -- Apply the HelperLoopCorrect definition to h_helperLoopCorrect.
      obtain ⟨h_taken, h_target, h_minimal⟩ := h_helperLoopCorrect;
      split_ifs <;> simp_all +decide [ TargetSatisfied ];
      · cases h_target <;> simp_all +decide [ List.take_of_length_le ];
      · -- Since $k > 0$, the first part of $h_target$ cannot hold, so we must have $0 = \text{length}(nums)$.
        have h_length_zero : 0 = nums.length := by
          exact h_target.resolve_left fun h => by linarith [ h 0 ] ;
        grind
