/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 3c2f791b-b658-4b0e-bc5d-af7dd23fd905

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
This module implements a solution to the missing number problem. It defines `missingNumber` which calculates the missing number in a list of `n` distinct integers from `0` to `n` using the summation formula. It also includes a formal proof `missingNumber_spec_satisfied` verifying that the function correctly identifies the missing number.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

@[reducible]
def missingNumber_precond (nums : List Nat) : Prop :=
  nums.all (fun x => x ≤ nums.length) ∧ List.Nodup nums

def missingNumber (nums : List Nat) (h_precond : missingNumber_precond (nums)) : Nat :=
  let n := nums.length
  let expectedSum := (n * (n + 1)) / 2
  let actualSum := nums.foldl (· + ·) 0
  expectedSum - actualSum

@[reducible]
def missingNumber_postcond (nums : List Nat) (result: Nat) (h_precond : missingNumber_precond (nums)) : Prop :=
  let n := nums.length
  (result ∈ List.range (n + 1)) ∧
  ¬(result ∈ nums) ∧
  ∀ x, (x ∈ List.range (n + 1)) → x ≠ result → x ∈ nums

theorem missingNumber_spec_satisfied (nums: List Nat) (h_precond : missingNumber_precond (nums)) :
    missingNumber_postcond (nums) (missingNumber (nums) h_precond) h_precond := by
  -- By definition of `missingNumber`, we know that `missingNumber nums h_precond` is the sum of the first `n + 1` natural numbers minus the sum of `nums`.
  have h_sum : (missingNumber nums h_precond) = (∑ i ∈ Finset.range (nums.length + 1), i) - (∑ i ∈ Finset.range (nums.length), nums[i]!) := by
    unfold missingNumber;
    -- The sum of the first `n + 1` natural numbers is given by the formula `n * (n + 1) / 2`.
    have h_sum_formula : ∑ i ∈ Finset.range (nums.length + 1), i = nums.length * (nums.length + 1) / 2 := by
      simp +arith +decide [ mul_comm, Finset.sum_range_id ];
    simp +decide [ h_sum_formula, Finset.sum_range, List.sum_eq_foldl ];
  -- By definition of `missingNumber`, we know that `missingNumber nums h_precond` is the sum of the first `n + 1` natural numbers minus the sum of `nums`, which is exactly the missing number.
  have h_missing : ∑ i ∈ Finset.range (nums.length + 1), i = ∑ i ∈ Finset.range (nums.length), nums[i]! + (missingNumber nums h_precond) := by
    rw [ h_sum, Nat.add_sub_of_le ];
    -- Since `nums` contains all numbers from `0` to `n-1` except one, we can pair each element in `nums` with its corresponding element in the range `[0, n]`.
    have h_pair : ∑ i ∈ Finset.range (nums.length), nums[i]! ≤ ∑ i ∈ Finset.image (fun i => nums[i]!) (Finset.range (nums.length)), i := by
      rw [ Finset.sum_image ];
      -- Since `nums` is a list of distinct numbers, if `nums[i]! = nums[j]!`, then `i = j`.
      have h_inj : ∀ i j, i < nums.length → j < nums.length → nums[i]! = nums[j]! → i = j := by
        have := List.nodup_iff_injective_get.mp h_precond.2;
        -- Since `nums` is a list of distinct numbers, if `nums[i]! = nums[j]!`, then `i = j` by the injectivity of `nums.get`.
        intros i j hi hj h_eq
        have := @this ⟨i, hi⟩ ⟨j, hj⟩
        aesop;
      exact fun i hi j hj hij => h_inj i j ( Finset.mem_range.mp hi ) ( Finset.mem_range.mp hj ) hij;
    refine le_trans h_pair ?_;
    refine Finset.sum_le_sum_of_subset ?_;
    grind;
  -- Since `nums` contains all numbers from `0` to `n` except one, it must be a permutation of `Finset.range (nums.length + 1)` with one element missing.
  have h_perm : Finset.image (fun i => nums[i]!) (Finset.range (nums.length)) ⊆ Finset.range (nums.length + 1) ∧ Finset.card (Finset.image (fun i => nums[i]!) (Finset.range (nums.length))) = nums.length := by
    -- Since `nums` contains all numbers from `0` to `n` except one, the image of `nums[i]!` over the range of `nums.length` is exactly the set of elements in `nums`.
    have h_image : Finset.image (fun i => nums[i]!) (Finset.range (nums.length)) = nums.toFinset := by
      -- By definition of `List.toFinset`, the image of the function `fun i => nums[i]!` over the range of `nums.length` is exactly the set of elements in `nums`.
      ext; simp [List.mem_toFinset];
      -- By definition of `List.mem_iff_get?`, if `x` is in `nums`, then there exists an index `i` such that `nums[i] = x`.
      apply Iff.intro;
      · grind;
      · intro hx; rw [ List.mem_iff_get ] at hx; obtain ⟨ i, hi ⟩ := hx; use i; aesop;
    -- Since `nums` contains all numbers from `0` to `n` except one, the image of `nums[i]!` over the range of `nums.length` is exactly the set of elements in `nums`, which has cardinality `nums.length`.
    have h_card : Finset.card (Finset.image (fun i => nums[i]!) (Finset.range (nums.length))) = nums.length := by
      rw [ h_image, List.toFinset_card_of_nodup ] ; aesop;
    grind;
  -- Since `Finset.image (fun i => nums[i]!) (Finset.range (nums.length))` is a subset of `Finset.range (nums.length + 1)` with cardinality `nums.length`, it must be equal to `Finset.range (nums.length + 1)` minus one element.
  obtain ⟨x, hx⟩ : ∃ x ∈ Finset.range (nums.length + 1), Finset.image (fun i => nums[i]!) (Finset.range (nums.length)) = Finset.range (nums.length + 1) \ {x} := by
    have h_perm : Finset.card (Finset.range (nums.length + 1) \ Finset.image (fun i => nums[i]!) (Finset.range (nums.length))) = 1 := by
      grind;
    obtain ⟨ x, hx ⟩ := Finset.card_eq_one.mp h_perm;
    exact ⟨ x, Finset.mem_sdiff.mp ( hx.symm ▸ Finset.mem_singleton_self _ ) |>.1, by rw [ ← hx, Finset.sdiff_sdiff_eq_self ( by tauto ) ] ⟩;
  -- Since `Finset.image (fun i => nums[i]!) (Finset.range (nums.length))` is equal to `Finset.range (nums.length + 1)` minus one element, we can conclude that `missingNumber nums h_precond` is exactly that missing element.
  have h_missing_eq : missingNumber nums h_precond = x := by
    have h_missing_eq : ∑ i ∈ Finset.range (nums.length), nums[i]! = ∑ i ∈ Finset.range (nums.length + 1), i - x := by
      have h_missing_eq : ∑ i ∈ Finset.range (nums.length), nums[i]! = ∑ i ∈ Finset.image (fun i => nums[i]!) (Finset.range (nums.length)), i := by
        rw [ Finset.sum_image ];
        intro i hi j hj hij; have := Finset.card_image_iff.mp ( by aesop : Finset.card ( Finset.image ( fun i => nums[i]! ) ( Finset.range nums.length ) ) = Finset.card ( Finset.range nums.length ) ) ; aesop;
      rw [ h_missing_eq, hx.2, Finset.sum_eq_sum_diff_singleton_add hx.1 ] ; norm_num;
    rw [ h_sum, h_missing_eq, Nat.sub_sub_self ( Finset.single_le_sum ( fun i _ => Nat.zero_le i ) ( Finset.mem_range.mpr ( Finset.mem_range.mp hx.1 ) ) ) ];
  refine' ⟨ _, _, _ ⟩ <;> simp_all +decide [ Finset.ext_iff ];
  · intro hx';
    obtain ⟨ i, hi ⟩ := List.mem_iff_get.1 hx';
    specialize hx ; have := hx.2 x ; simp_all +decide [ Finset.mem_image ];
    exact hx.2 x |>.1 ⟨ i, i.2, by simp +decide [ hi ] ⟩ |>.2 rfl;
  · grind
