/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 2c487f79-f27e-494a-8a39-ffd13dba5a4f

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
We define `removeElement` which removes all occurrences of a target number from a list of natural numbers. We prove `removeElement_spec_satisfied`, showing that the function correctly filters out the target element while preserving the order of other elements.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

@[reducible]
def removeElement_precond (lst : List Nat) (target : Nat) : Prop :=
  True

def removeElement (lst : List Nat) (target : Nat) (h_precond : removeElement_precond (lst) (target)) : List Nat :=
  let rec helper (lst : List Nat) (target : Nat) : List Nat :=
    match lst with
    | [] => []
    | x :: xs =>
      let rest := helper xs target
      if x = target then rest else x :: rest
  helper lst target

@[reducible]
def removeElement_postcond (lst : List Nat) (target : Nat) (result: List Nat) (h_precond : removeElement_precond (lst) (target)): Prop :=
  let lst' := lst.filter (fun x => x ≠ target)
  result.zipIdx.all (fun (x, i) =>
    match lst'[i]? with
    | some y => x = y
    | none => false) ∧ result.length = lst'.length

theorem removeElement_spec_satisfied (lst: List Nat) (target: Nat) (h_precond : removeElement_precond (lst) (target)):
    removeElement_postcond (lst) (target) (removeElement (lst) (target) h_precond) h_precond := by
  -- By definition of `removeElement`, we know that `removeElement lst target h_precond` is equivalent to `lst.filter (fun x => x ≠ target)`.
  have h_eq : removeElement lst target h_precond = lst.filter (fun x => x ≠ target) := by
    -- By definition of `removeElement.helper`, we can prove this by induction on `lst`.
    have h_helper : ∀ (lst : List ℕ) (target : ℕ), removeElement.helper lst target = lst.filter (fun x => x ≠ target) := by
      -- We'll use induction on the list to prove that the helper function is equivalent to the filter function.
      intro lst target
      induction' lst with x xs ih;
      · rfl;
      · -- By definition of `removeElement.helper`, we have:
        simp [removeElement.helper, ih];
        grind
    generalize_proofs at *; simp_all +decide [ removeElement ] ;
  grind
