/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: c5679e55-af34-4626-8f99-449b2d9ddb0c

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
We have successfully loaded the user's code and verified the correctness of the `searchInsert` function by proving `searchInsert_spec_satisfied`. The ATP was able to automatically prove the theorem without additional helper lemmas.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

@[reducible]
def searchInsert_precond (xs : List Int) (target : Int) : Prop :=
  List.Pairwise (· < ·) xs

def searchInsert (xs : List Int) (target : Int) (h_precond : searchInsert_precond (xs) (target)) : Nat :=
  match xs with
  | [] =>
      0
  | _ :: _ =>
      let rec helper : List Int → Nat → Nat :=
        fun ys idx =>
          match ys with
          | [] =>
              idx
          | y :: ys' =>
              let isCurrent := y
              let currentIndex := idx
              let targetValue := target
              let condition := targetValue ≤ isCurrent
              if condition then
                currentIndex
              else
                let incrementedIndex := currentIndex + 1
                let rest := ys'
                helper rest incrementedIndex
      let startingIndex := 0
      let result := helper xs startingIndex
      result

@[reducible]
def searchInsert_postcond (xs : List Int) (target : Int) (result: Nat) (h_precond : searchInsert_precond (xs) (target)) : Prop :=
  let allBeforeLess := (List.range result).all (fun i => xs[i]! < target)
  let inBounds := result ≤ xs.length
  let insertedCorrectly :=
    result < xs.length → target ≤ xs[result]!
  inBounds ∧ allBeforeLess ∧ insertedCorrectly

theorem searchInsert_spec_satisfied (xs: List Int) (target: Int) (h_precond : searchInsert_precond (xs) (target)) :
    searchInsert_postcond (xs) (target) (searchInsert (xs) (target) h_precond) h_precond := by
  unfold searchInsert_postcond searchInsert;
  -- We'll use induction on the length of the tail to prove the properties of the helper function.
  have h_ind : ∀ (xs : List ℤ) (target : ℤ) (h_precond : searchInsert_precond xs target), (∀ (i : ℕ), i < searchInsert.helper target xs 0 → (xs[i]!) < target) ∧ (searchInsert.helper target xs 0 ≤ xs.length) ∧ (searchInsert.helper target xs 0 < xs.length → target ≤ xs[(searchInsert.helper target xs 0)]!) := by
    -- We'll use induction on the length of the list to prove the properties of the helper function.
    intro xs target h_precond
    induction' xs with x xs ih generalizing target;
    · simp [searchInsert.helper];
    · -- By definition of `searchInsert.helper`, we know that it returns the correct index where the target should be inserted in the list `x :: xs`.
      simp [searchInsert.helper] at *;
      -- By definition of `searchInsert.helper`, we know that it returns the correct index where the target should be inserted in the list `x :: xs`. We can use the induction hypothesis on `xs` with the starting index 1.
      have h_ind : searchInsert.helper target xs 1 = searchInsert.helper target xs 0 + 1 := by
        have h_ind : ∀ (xs : List ℤ) (target : ℤ) (start : ℕ), searchInsert.helper target xs (start + 1) = searchInsert.helper target xs start + 1 := by
          intros xs target start; induction' xs with x xs ih generalizing target start <;> simp +decide [ *, searchInsert.helper ] ;
          split_ifs <;> ring;
        apply h_ind;
      grind;
  specialize h_ind _ _ h_precond ; aesop
