/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: fe9d05fd-5b15-42fe-85db-9c7e5b867da0

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
This module implements a function `mostFrequent` that finds the most frequent integer in a list, returning the first occurrence in case of a tie. It includes helper functions `countMap`, `getMaxFrequency`, `getCandidates`, and `getFirstWithFreq`. The correctness of `mostFrequent` is formally verified by the theorem `mostFrequent_spec_satisfied`, which ensures the result is in the list, has the maximum frequency, and is the first such element.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

open Std

@[reducible]
def mostFrequent_precond (xs : List Int) : Prop :=
  xs ≠ []

def countMap (xs : List Int) : HashMap Int Nat :=
  let step := fun m x =>
    let current := m.getD x 0
    m.insert x (current + 1)
  let init := (HashMap.empty : HashMap Int Nat)
  xs.foldl step init

def getMaxFrequency (m : HashMap Int Nat) : Nat :=
  let step := fun acc (_k, v) =>
    if v > acc then v else acc
  let init := 0
  m.toList.foldl step init

def getCandidates (m : HashMap Int Nat) (maxFreq : Nat) : List Int :=
  let isTarget := fun (_k, v) => v = maxFreq
  let extract := fun (k, _) => k
  m.toList.filter isTarget |>.map extract

def getFirstWithFreq (xs : List Int) (candidates : List Int) : Int :=
  match xs.find? (fun x => candidates.contains x) with
  | some x => x
  | none => 0

def mostFrequent (xs : List Int) (h_precond : mostFrequent_precond (xs)) : Int :=
  let freqMap := countMap xs
  let maxF := getMaxFrequency freqMap
  let candidates := getCandidates freqMap maxF
  getFirstWithFreq xs candidates

@[reducible]
def mostFrequent_postcond (xs : List Int) (result: Int) (h_precond : mostFrequent_precond (xs)) : Prop :=
  let count := fun x => xs.countP (fun y => y = x)
  result ∈ xs ∧
  xs.all (fun x => count x ≤ count result) ∧
  ((xs.filter (fun x => count x = count result)).head? = some result)

theorem countMap_foldl_spec (xs : List Int) (m : HashMap Int Nat) (y : Int) :
    (xs.foldl (fun m x => m.insert x (m.getD x 0 + 1)) m).getD y 0 = m.getD y 0 + xs.countP (fun z => z = y) := by
  -- We can prove this by induction on the list xs.
  induction' xs with x xs ih generalizing m;
  · grind;
  · grind

theorem countMap_countP (xs : List Int) (x : Int) :
    (countMap xs).getD x 0 = xs.countP (fun y => y = x) := by
  -- Apply the `countMap_foldl_spec` lemma with `m` being the empty map.
  have h_count : (xs.foldl (fun m x => m.insert x (m.getD x 0 + 1)) (HashMap.empty : HashMap Int Nat)).getD x 0 = 0 + xs.countP (fun y => y = x) := by
    -- Apply the `countMap_foldl_spec` lemma with `m` being the empty map and `y` being `x`.
    have h_count : (xs.foldl (fun m x => m.insert x (m.getD x 0 + 1)) (HashMap.empty : HashMap Int Nat)).getD x 0 = (HashMap.empty : HashMap Int Nat).getD x 0 + xs.countP (fun y => y = x) := by
      -- Apply the `countMap_foldl_spec` lemma with `m` being the empty map and `y` being `x` to conclude the proof.
      apply countMap_foldl_spec;
    grind;
  -- Since the countMap is defined as the result of folding the step function over xs starting with an empty map, the two expressions are identical.
  convert h_count using 1;
  -- The count of x in xs is equal to itself plus zero, which is trivially true.
  simp [zero_add]

theorem getMaxFrequency_upper_bound (m : HashMap Int Nat) (k : Int) (v : Nat) :
    (k, v) ∈ m.toList → v ≤ getMaxFrequency m := by
  -- By definition of `getMaxFrequency`, it is the maximum value in the list of values from `m`.
  have h_max : ∀ {l : List (ℤ × ℕ)}, (k, v) ∈ l → v ≤ List.foldl (fun acc (k, v) => if v > acc then v else acc) 0 l := by
    -- By definition of `List.foldl`, the result is the maximum value in the list.
    have h_max : ∀ {l : List (ℤ × ℕ)}, ∀ x ∈ l, x.2 ≤ List.foldl (fun acc (k, v) => if v > acc then v else acc) 0 l := by
      -- By induction on the list, we can show that the foldl result is at least as large as any element's value.
      intros l x hx
      induction' l using List.reverseRecOn with l ih generalizing x;
      · contradiction;
      · grind;
    exact fun { l } hl => h_max _ hl;
  -- Apply the hypothesis `h_max` to the list `m.toList` and the fact that `(k, v)` is in that list.
  apply h_max

theorem getMaxFrequency_is_max (xs : List Int) (x : Int) :
    xs.countP (fun y => y = x) ≤ getMaxFrequency (countMap xs) := by
  -- The count of x in xs is exactly the value of x in the countMap.
  have h_count_x : (xs.countP (fun y => y = x)) = (countMap xs).getD x 0 := by
    exact?;
  -- By definition of `getMaxFrequency`, we know that every element in the countMap has a value less than or equal to `getMaxFrequency`.
  have h_max_le : ∀ (m : HashMap Int Nat) (k : Int) (v : Nat), (k, v) ∈ m.toList → v ≤ getMaxFrequency m := by
    exact?;
  by_cases hx : x ∈ xs;
  · convert h_max_le ( countMap xs ) x ( List.countP ( fun y => y = x ) xs ) _ using 1;
    simp_all +decide [ List.countP_eq_length_filter ];
    have h_count_x_in_map : x ∈ countMap xs := by
      have h_countMap_contains_x : ∀ {xs : List ℤ} {x : ℤ}, x ∈ xs → x ∈ List.foldl (fun (m : Std.HashMap ℤ ℕ) (x : ℤ) => m.insert x (m.getD x 0 + 1)) (Std.HashMap.empty) xs := by
        intros xs x hx; induction' xs using List.reverseRecOn with xs x ih <;> aesop;
      exact h_countMap_contains_x hx;
    exact?;
  · rw [ List.countP_eq_zero.mpr ] <;> aesop

theorem getCandidates_mem (m : HashMap Int Nat) (maxFreq : Nat) (x : Int) :
    x ∈ getCandidates m maxFreq ↔ (x, maxFreq) ∈ m.toList := by
  -- By definition of `getCandidates`, `x` is in the candidates if and only if there exists a key-value pair `(k, v)` in `m.toList` such that `v = maxFreq` and `k = x`.
  simp [getCandidates]

theorem candidates_nonempty (xs : List Int) (h : xs ≠ []) :
    getCandidates (countMap xs) (getMaxFrequency (countMap xs)) ≠ [] := by
  -- Since `xs` is non-empty, there must be at least one element in the count map.
  obtain ⟨k, hk⟩ : ∃ k, (k, getMaxFrequency (countMap xs)) ∈ (countMap xs).toList := by
    -- Since the countMap is non-empty, there must be at least one element in the countMap with the maximum frequency.
    have h_nonempty : (countMap xs).toList ≠ [] := by
      -- Since `xs` is non-empty, there must be at least one element in the countMap.
      have h_countMap_nonempty : ∃ x ∈ xs, (countMap xs).getD x 0 > 0 := by
        -- Since `xs` is non-empty, there must be at least one element in `xs` that appears at least once.
        obtain ⟨x, hx⟩ : ∃ x ∈ xs, True := by
          exact Exists.elim ( List.length_pos_iff_exists_mem.mp ( List.length_pos_iff.mpr h ) ) fun x hx => ⟨ x, hx, trivial ⟩;
        use x;
        -- Since x is in xs, by definition of countMap, the count of x is at least 1.
        have h_count_pos : (countMap xs).getD x 0 = xs.countP (fun y => y = x) := by
          exact?;
        exact ⟨ hx.1, h_count_pos.symm ▸ by rw [ List.countP_eq_length_filter ] ; exact List.length_pos_iff.mpr ( by aesop ) ⟩;
      -- Since there exists an x in xs with a positive count, the countMap must contain x, making the list non-empty.
      obtain ⟨x, hx⟩ : ∃ x ∈ xs, (countMap xs).getD x 0 > 0 := h_countMap_nonempty;
      have h_countMap_nonempty : x ∈ (countMap xs).keys := by
        -- Since x is in xs, it must be present in the countMap.
        have h_x_in_countMap : x ∈ (countMap xs).keys := by
          have h_foldl : ∀ (xs : List ℤ) (x : ℤ), x ∈ xs → x ∈ (List.foldl (fun (m : Std.HashMap ℤ ℕ) (x : ℤ) => m.insert x (m.getD x 0 + 1)) (Std.HashMap.empty) xs).keys := by
            intros xs x hx; induction' xs using List.reverseRecOn with xs x ih <;> aesop;
          exact h_foldl xs x hx.left;
        exact h_x_in_countMap;
      grind;
    -- Since the list is non-empty, there must be some element in it.
    obtain ⟨x, hx⟩ : ∃ x ∈ (countMap xs).toList, x.snd = getMaxFrequency (countMap xs) := by
      have h_max_in_list : ∀ {l : List (Int × Nat)}, l ≠ [] → ∃ x ∈ l, x.2 = List.foldl (fun acc (k, v) => if v > acc then v else acc) 0 l := by
        intros l hl_nonempty
        induction' l using List.reverseRecOn with l ih;
        · contradiction;
        · by_cases hl : l = [] <;> simp_all +decide [ List.foldl_append ];
          split_ifs <;> aesop;
      exact h_max_in_list h_nonempty;
    grind;
  -- Since `k` is a candidate, the candidates list is non-empty.
  have h_candidates_nonempty : k ∈ getCandidates (countMap xs) (getMaxFrequency (countMap xs)) := by
    exact?;
  exact List.ne_nil_of_mem h_candidates_nonempty

theorem candidates_subset_xs (xs : List Int) (x : Int) :
    x ∈ getCandidates (countMap xs) (getMaxFrequency (countMap xs)) → x ∈ xs := by
  -- If x is in the candidates list, then there exists a pair (k, v) in the countMap's toList such that k = x and v = maxFreq.
  intro hx
  obtain ⟨k, v, hk, hv⟩ : ∃ k v, (k, v) ∈ (countMap xs).toList ∧ k = x ∧ v = getMaxFrequency (countMap xs) := by
    unfold getCandidates at hx; aesop;
  have h_exists : k ∈ (countMap xs).keys := by
    grind;
  have h_exists : ∀ {xs : List ℤ} {x : ℤ}, x ∈ (List.foldl (fun (m : Std.HashMap ℤ ℕ) (x : ℤ) => m.insert x (m.getD x 0 + 1)) Std.HashMap.empty xs).keys → x ∈ xs := by
    intros xs x hx; induction' xs using List.reverseRecOn with xs x ih <;> aesop;
  exact hv.1 ▸ h_exists ‹_›

theorem maxFreq_pos (xs : List Int) (h : xs ≠ []) :
    getMaxFrequency (countMap xs) > 0 := by
  -- Since `xs` is non-empty, there must be at least one element in `xs` with a positive frequency.
  obtain ⟨x, hx⟩ : ∃ x ∈ xs, 0 < xs.countP (fun y => y = x) := by
    -- Since `xs` is non-empty, there must be at least one element in `xs` with a positive frequency. We can take any element from `xs` and show that its count is at least one.
    obtain ⟨x, hx⟩ : ∃ x, x ∈ xs := by
      exact List.length_pos_iff_exists_mem.mp ( List.length_pos_iff.mpr h );
    -- Since x is in xs, the count of x in xs is at least 1.
    use x, hx
    simp [hx];
  -- Since the count of x in xs is positive, and the maximum frequency is the highest count, this implies that the maximum frequency must be at least as large as the count of x.
  have h_max_ge_count : getMaxFrequency (countMap xs) ≥ xs.countP (fun y => y = x) := by
    -- Apply the theorem that states the count of any element in the list is less than or equal to the maximum frequency in the countMap.
    apply getMaxFrequency_is_max;
  grind

theorem mem_candidates_iff_maxFreq (xs : List Int) (h : xs ≠ []) (x : Int) :
    x ∈ getCandidates (countMap xs) (getMaxFrequency (countMap xs)) ↔
    xs.countP (fun y => y = x) = getMaxFrequency (countMap xs) := by
  -- By definition of `getCandidates`, `x` is in the candidates if and only if `(x, getMaxFrequency (countMap xs))` is in the list of pairs from the countMap.
  simp [getCandidates];
  -- By definition of `countMap`, the value at key `x` in the countMap is the count of `x` in `xs`.
  have h_countMap : ∀ x, (countMap xs).getD x 0 = xs.countP (fun y => y = x) := by
    -- By definition of `countMap`, we know that `(countMap xs).getD x 0` is the count of `x` in `xs` because the foldl operation correctly accumulates the counts.
    intros x
    apply countMap_countP;
  by_cases hx : x ∈ (countMap xs).keys <;> simp_all +decide [ HashMap.getElem?_eq_none ];
  · rw [ ← h_countMap ];
    -- Since x is in the countMap, the value at x is exactly the count of x in xs. Therefore, the equality (countMap xs)[x] = getMaxFrequency (countMap xs) holds if and only if the count of x in xs is equal to the maximum frequency.
    have h_eq : (countMap xs)[x] = (countMap xs).getD x 0 := by
      exact?;
    rw [h_eq];
  · -- Since x is not in the countMap, its count in xs is zero.
    have h_count_zero : (countMap xs).getD x 0 = 0 := by
      exact?;
    exact ne_of_lt ( h_countMap x ▸ h_count_zero.symm ▸ maxFreq_pos xs h )

theorem mostFrequent_in_candidates (xs : List Int) (h : xs ≠ []) :
    mostFrequent xs h ∈ getCandidates (countMap xs) (getMaxFrequency (countMap xs)) := by
  -- By definition of `getFirstWithFreq`, the result is the first element in `xs` that is in the candidates.
  have h_first_in_candidates : ∃ x ∈ xs, x ∈ getCandidates (countMap xs) (getMaxFrequency (countMap xs)) := by
    -- By definition of `candidates_nonempty`, there exists at least one element in the candidates list.
    obtain ⟨x, hx⟩ : ∃ x, x ∈ getCandidates (countMap xs) (getMaxFrequency (countMap xs)) := by
      exact List.length_pos_iff_exists_mem.mp ( List.length_pos_iff.mpr ( candidates_nonempty xs h ) );
    exact ⟨ x, candidates_subset_xs xs x hx, hx ⟩;
  -- By definition of `find?`, if there exists an element in `xs` that is in the candidates, then `find?` will return the first such element.
  obtain ⟨x, hx₁, hx₂⟩ := h_first_in_candidates;
  have h_find : xs.find? (fun x => (getCandidates (countMap xs) (getMaxFrequency (countMap xs))).contains x) = some (mostFrequent xs h) := by
    unfold mostFrequent;
    unfold getFirstWithFreq; aesop;
  grind

theorem mostFrequent_spec_satisfied (xs: List Int) (h_precond : mostFrequent_precond (xs)) :
    mostFrequent_postcond (xs) (mostFrequent (xs) h_precond) h_precond := by
  -- By definition of `mostFrequent`, we know that the result is in `xs`, all elements have a count ≤ the count of the result, and the first occurrence of the result in `xs` is the result itself.
  apply And.intro;
  · exact candidates_subset_xs _ _ ( mostFrequent_in_candidates _ h_precond );
  · apply And.intro;
    · have h_count_le_max : ∀ x ∈ xs, xs.countP (fun y => y = x) ≤ getMaxFrequency (countMap xs) := by
        exact?;
      have h_count_eq_max : xs.countP (fun y => y = mostFrequent xs h_precond) = getMaxFrequency (countMap xs) := by
        apply (mem_candidates_iff_maxFreq xs h_precond (mostFrequent xs h_precond)).mp (mostFrequent_in_candidates xs h_precond);
      grind;
    · -- By definition of `getFirstWithFreq`, the result is the first element in `xs` that is in the candidates.
      have h_first_in_candidates : mostFrequent xs h_precond ∈ xs ∧ (xs.find? (fun x => (getCandidates (countMap xs) (getMaxFrequency (countMap xs))).contains x)) = some (mostFrequent xs h_precond) := by
        unfold mostFrequent;
        field_simp;
        unfold getFirstWithFreq;
        -- Since `xs` is non-empty, `find?` will return `some x` for some `x` in `xs`.
        have h_find_some : ∃ x, List.find? (fun x => (getCandidates (countMap xs) (getMaxFrequency (countMap xs))).contains x) xs = some x := by
          have h_find_some : ∃ x, x ∈ xs ∧ (getCandidates (countMap xs) (getMaxFrequency (countMap xs))).contains x := by
            have h_firstOccurrence : mostFrequent xs h_precond ∈ getCandidates (countMap xs) (getMaxFrequency (countMap xs)) := by
              exact?;
            exact ⟨ _, candidates_subset_xs _ _ h_firstOccurrence, by simpa using h_firstOccurrence ⟩;
          cases h : List.find? ( fun x => ( getCandidates ( countMap xs ) ( getMaxFrequency ( countMap xs ) ) ).contains x ) xs <;> aesop;
        -- Since `find?` returns `some x`, we can conclude that `x` is in `xs` and the `find?` result is `some x`.
        obtain ⟨x, hx⟩ := h_find_some;
        rw [hx];
        simp;
        exact?;
      -- By definition of `find?`, the result is the first element in `xs` that satisfies the predicate.
      have h_find_eq_filter : ∀ {l : List ℤ} {p : ℤ → Bool}, List.find? p l = some (mostFrequent xs h_precond) → List.head? (List.filter p l) = some (mostFrequent xs h_precond) := by
        grind;
      convert h_find_eq_filter h_first_in_candidates.2 using 3;
      -- By definition of `getCandidates`, we know that `x` is in `getCandidates` if and only if `x`'s count is equal to the maximum frequency.
      have h_candidates_eq : ∀ x, x ∈ getCandidates (countMap xs) (getMaxFrequency (countMap xs)) ↔ xs.countP (fun y => y = x) = getMaxFrequency (countMap xs) := by
        exact?;
      grind
