/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: fe4e7da0-be65-48a3-864e-a224b483d99e

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
This module implements a function `removeDuplicates` that counts the number of unique elements in a sorted list of integers. It defines a precondition `removeDuplicates_precond` ensuring the input list is sorted, and a postcondition `removeDuplicates_postcond` asserting that the result matches the length of the list with duplicates removed. Finally, it proves `removeDuplicates_spec_satisfied`, confirming that the implementation satisfies the postcondition given the precondition.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

@[reducible]
def removeDuplicates_precond (nums : List Int) : Prop :=
  -- !benchmark @start precond
  -- nums are sorted in non-decreasing order
  List.Pairwise (· ≤ ·) nums
  -- !benchmark @end precond

def removeDuplicates (nums : List Int) (h_precond : removeDuplicates_precond (nums)) : Nat :=
  -- !benchmark @start code
  match nums with
  | [] =>
    0
  | h :: t =>
    let init := h
    let initCount := 1
    let rec countUniques (prev : Int) (xs : List Int) (k : Nat) : Nat :=
      match xs with
      | [] =>
        k
      | head :: tail =>
        let isDuplicate := head = prev
        if isDuplicate then
          countUniques prev tail k
        else
          let newK := k + 1
          countUniques head tail newK
    countUniques init t initCount
  -- !benchmark @end code

@[reducible]
def removeDuplicates_postcond (nums : List Int) (result: Nat) (h_precond : removeDuplicates_precond (nums)) : Prop :=
  -- !benchmark @start postcond
  result - nums.eraseDups.length = 0 ∧
  nums.eraseDups.length ≤ result
  -- !benchmark @end postcond

theorem removeDuplicates_spec_satisfied (nums: List Int) (h_precond : removeDuplicates_precond (nums)) :
    removeDuplicates_postcond (nums) (removeDuplicates (nums) h_precond) h_precond := by
  -- !benchmark @start proof
  -- By definition of `removeDuplicates`, we know that `removeDuplicates nums h_precond` is equal to `nums.eraseDups.length`.
  have h_eq : removeDuplicates nums h_precond = nums.eraseDups.length := by
    unfold removeDuplicates;
    induction' nums with h t ih ; aesop;
    rcases t with ( _ | ⟨ h', t' ⟩ ) <;> simp_all +decide;
    · rfl;
    · -- By definition of `countUniques`, we can split into cases based on whether `h` equals `h'`.
      by_cases h_eq : h = h';
      · simp_all +decide [ removeDuplicates.countUniques, List.eraseDups_cons ];
      · -- Since h is not equal to h', the countUniques function will add 1 to the count and then proceed with the rest of the list.
        have h_count : removeDuplicates.countUniques h (h' :: t') 1 = removeDuplicates.countUniques h' t' 2 := by
          -- By definition of `countUniques`, we can split into cases based on whether `h` equals `h'`. Since `h ≠ h'`, we can simplify the expression.
          simp [removeDuplicates.countUniques, h_eq];
          aesop;
        -- By definition of `countUniques`, we can split into cases based on whether `h` equals `h'`. Since $h \neq h'$, the countUniques function will increment the count by 1 and then process the rest of the list $t'$ starting from $h'$.
        have h_count : removeDuplicates.countUniques h' t' 2 = removeDuplicates.countUniques h' t' 1 + 1 := by
          have h_count : ∀ (prev : ℤ) (xs : List ℤ) (k : ℕ), removeDuplicates.countUniques prev xs (k + 1) = removeDuplicates.countUniques prev xs k + 1 := by
            intros prev xs k; induction' xs with x xs ih generalizing prev k <;> simp_all +decide [ removeDuplicates.countUniques ] ;
            split_ifs <;> ring;
          apply h_count;
        -- Since $h \neq h'$, the filter condition `!b == h` will remove $h$ from the list, leaving us with the same list as when we started with $h'$.
        have h_filter : List.filter (fun b => !b == h) (h' :: t') = h' :: List.filter (fun b => !b == h) t' := by
          grind;
        simp_all +decide [ List.eraseDups_cons ];
        congr! 2;
        -- Since $h \neq h'$, the condition $!a == h'$ implies $!a == h$, so the two filters are equivalent.
        have h_filter_eq : ∀ a ∈ t', !a == h' → !a == h := by
          grind;
        exact List.filter_congr fun x hx => by specialize h_filter_eq x hx; by_cases h : !x == h' <;> aesop;
  unfold removeDuplicates_postcond; aesop;
  -- !benchmark @end proof
