/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: b0a92664-5491-49bd-9222-c429e37e523f

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
We defined a function `reverseString` that reverses a string using a tail-recursive helper function. We also defined a precondition `reverseString_precond` (which is trivial) and a postcondition `reverseString_postcond` asserting that the result has the same length as the input and its characters are in reverse order. Finally, we proved `reverseString_spec_satisfied`, showing that `reverseString` satisfies the postcondition.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

@[reducible]
def reverseString_precond (s : String) : Prop :=
  True

def reverseString (s : String) (h_precond : reverseString_precond (s)) : String :=
  let rec reverseAux (chars : List Char) (acc : List Char) : List Char :=
    match chars with
    | [] => acc
    | h::t => reverseAux t (h::acc)
  String.mk (reverseAux (s.toList) [])

@[reducible]
def reverseString_postcond (s : String) (result: String) (h_precond : reverseString_precond (s)) : Prop :=
  result.length = s.length ∧ result.toList = s.toList.reverse

theorem reverseString_spec_satisfied (s: String) (h_precond : reverseString_precond (s)) :
    reverseString_postcond (s) (reverseString (s) h_precond) h_precond := by
  -- By definition of `reverseString`, we know that `reverseString s h_precond` is the reversed version of `s`.
  have h_rev : reverseString s h_precond = String.mk (s.toList.reverse) := by
    -- By definition of `reverseString`, we know that `reverseString s h_precond` is the reversed version of `s` because it applies `List.reverse` to the list of characters.
    simp [reverseString];
    -- By definition of `reverseAux`, we have `reverseAux s.data [] = s.data.reverse` because `reverseAux` is equivalent to `List.reverse`.
    have h_reverse_aux : ∀ (l : List Char) (acc : List Char), reverseString.reverseAux l acc = l.reverse ++ acc := by
      -- We can prove this by induction on the list `l`.
      intro l acc
      induction' l with h t ih generalizing acc;
      · rfl;
      · -- By definition of `reverseAux`, we have `reverseString.reverseAux (h :: t) acc = reverseString.reverseAux t (h :: acc)`.
        have h_def : reverseString.reverseAux (h :: t) acc = reverseString.reverseAux t (h :: acc) := by
          rfl
          skip
        generalize_proofs at *;
        aesop;
    -- By definition of `reverseAux`, we have `reverseString.reverseAux s.data [] = s.data.reverse ++ []`.
    simp [h_reverse_aux];
  -- Since reversing a string twice gives back the original string, the postcondition holds.
  simp [reverseString_postcond, h_rev]
