/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 6d5e2328-adc7-4873-b00d-0adbf31fe541

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
This module defines a function `partitionEvensOdds` that partitions a list of natural numbers into two lists: one containing all even numbers and the other containing all odd numbers, preserving their original order. It also includes a formal proof `partitionEvensOdds_spec_satisfied` verifying that the function correctly partitions the input list according to the postcondition `partitionEvensOdds_postcond`.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

@[reducible]
def partitionEvensOdds_precond (nums : List Nat) : Prop :=
  True

def partitionEvensOdds (nums : List Nat) (h_precond : partitionEvensOdds_precond (nums)) : (List Nat × List Nat) :=
  let rec helper (nums : List Nat) : (List Nat × List Nat) :=
    match nums with
    | [] => ([], [])
    | x :: xs =>
      let (evens, odds) := helper xs
      if x % 2 == 0 then (x :: evens, odds)
      else (evens, x :: odds)
  helper nums

@[reducible]
def partitionEvensOdds_postcond (nums : List Nat) (result: (List Nat × List Nat)) (h_precond : partitionEvensOdds_precond (nums)): Prop :=
  let evens := result.fst
  let odds := result.snd
  -- All elements from nums are in evens ++ odds, no extras
  evens ++ odds = nums.filter (fun n => n % 2 == 0) ++ nums.filter (fun n => n % 2 == 1) ∧
  evens.all (fun n => n % 2 == 0) ∧
  odds.all (fun n => n % 2 == 1)

theorem partitionEvensOdds_spec_satisfied (nums: List Nat) (h_precond : partitionEvensOdds_precond (nums)) :
    partitionEvensOdds_postcond (nums) (partitionEvensOdds (nums) h_precond) h_precond := by
  -- By definition of `partitionEvensOdds`, we know that `partitionEvensOdds nums h_precond` splits `nums` into even and odd elements.
  have h_split : partitionEvensOdds nums h_precond = (nums.filter (fun n => n % 2 == 0), nums.filter (fun n => n % 2 == 1)) := by
    -- By induction on the list, we can show that the helper function's result matches the filtered lists.
    have h_ind : ∀ (xs : List ℕ), partitionEvensOdds.helper xs = (List.filter (fun n => n % 2 == 0) xs, List.filter (fun n => n % 2 == 1) xs) := by
      intro xs
      induction' xs with x xs ih;
      · rfl;
      · unfold partitionEvensOdds.helper; aesop;
    exact h_ind _;
  -- By definition of `partitionEvensOdds`, we know that `partitionEvensOdds nums h_precond` splits `nums` into even and odd elements, so the postcondition holds.
  simp [h_split, partitionEvensOdds_postcond]
