/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: af3b53a4-3583-4fa2-b835-8e082829c897

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
I have formalized the `mergeSorted` function and proved that it satisfies the specification.
The solution includes:
- `mergeSorted_precond`: Precondition requiring input lists to be sorted.
- `mergeSortedAux`: Helper function implementing the merge logic.
- `mergeSorted`: Main function calling the helper.
- `mergeSorted_postcond`: Postcondition ensuring the result is sorted and a permutation of the combined inputs.
- `mergeSorted_spec_satisfied`: Theorem proving the correctness of the implementation.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

@[reducible, simp]
def mergeSorted_precond (a : List Int) (b : List Int) : Prop :=
  List.Pairwise (· ≤ ·) a ∧ List.Pairwise (· ≤ ·) b

def mergeSortedAux : List Int → List Int → List Int
| [], ys => ys
| xs, [] => xs
| x :: xs', y :: ys' =>
  if x ≤ y then
    let merged := mergeSortedAux xs' (y :: ys')
    x :: merged
  else
    let merged := mergeSortedAux (x :: xs') ys'
    y :: merged

def mergeSorted (a : List Int) (b : List Int) (h_precond : mergeSorted_precond (a) (b)) : List Int :=
  let merged := mergeSortedAux a b
  merged

@[reducible, simp]
def mergeSorted_postcond (a : List Int) (b : List Int) (result: List Int) (h_precond : mergeSorted_precond (a) (b)) : Prop :=
  List.Pairwise (· ≤ ·) result ∧
  List.isPerm result (a ++ b)

theorem mergeSorted_spec_satisfied (a: List Int) (b: List Int) (h_precond : mergeSorted_precond (a) (b)) :
    mergeSorted_postcond (a) (b) (mergeSorted (a) (b) h_precond) h_precond := by
  -- By definition of mergeSorted, we know that the result is a merge of a and b.
  have h_merge : mergeSorted a b h_precond = List.merge a b (· ≤ ·) := by
    -- By definition of `mergeSortedAux`, we know that it is equivalent to the `merge` function.
    have h_mergeAux_eq_merge : ∀ (a b : List ℤ), mergeSortedAux a b = List.merge a b (· ≤ ·) := by
      intros a b; induction' a with a ha generalizing b <;> induction' b with b hb generalizing a <;> simp +decide [ List.merge ] ;
      · native_decide +revert;
      · -- In the base case, when the first list is empty, the merge of the empty list and any list is just that list.
        simp [mergeSortedAux];
      · -- By definition of `mergeSortedAux`, when the second list is empty, it returns the first list.
        simp [mergeSortedAux];
      · unfold mergeSortedAux; aesop;
    exact h_mergeAux_eq_merge a b;
  -- Since a and b are both sorted, their merge is also sorted.
  have h_sorted : List.Pairwise (· ≤ ·) (a.merge b (· ≤ ·)) := by
    -- By definition of mergeSorted, we know that the result is a merge of a and b, which is sorted. We can use the fact that the merge of two sorted lists is also sorted.
    have h_sorted : ∀ (a b : List ℤ), List.Sorted (· ≤ ·) a → List.Sorted (· ≤ ·) b → List.Sorted (· ≤ ·) (List.merge a b (· ≤ ·)) := by
      exact?;
    exact h_sorted a b h_precond.1 h_precond.2;
  have h_perm : List.Perm (a.merge b (· ≤ ·)) (a ++ b) := by
    exact?;
  simp_all +decide [ List.isPerm_iff ]
