/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: b6d0eeb2-9b10-471d-95f4-ccc72c469125

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
I have successfully loaded the user's code and the ATP has proven the correctness theorem `solution_spec_satisfied`. The solution correctly implements the logic described in the problem statement, calculating the sum of squared distinct counts for all subarrays. The proof verifies that the implementation matches the postcondition specification.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

open Std

@[reducible]
def solution_precond (nums : List Nat) : Prop :=
  1 ≤ nums.length ∧ nums.length ≤ 100 ∧ nums.all (fun x => 1 ≤ x ∧ x ≤ 100)

def solution (nums : List Nat) : Nat :=
  let n := nums.length
  let subarray := fun (i j : Nat) => (nums.drop i).take (j - i + 1)
  let distinctCount := fun (l : List Nat) =>
    let hashSet := l.foldl (fun (s : HashSet Nat) a => s.insert a) HashSet.empty
    hashSet.size
  List.range n |>.foldl (fun acc i =>
    acc +
      (List.range (n - i) |>.foldl (fun acc' d =>
        let subarr := subarray i (i + d)
        let cnt := distinctCount subarr
        acc' + cnt * cnt
      ) 0)
  ) 0

@[reducible]
def solution_postcond (nums : List Nat) (result: Nat) : Prop :=
  let n := nums.length;

  let getSubarray_local := fun (i j : Nat) =>
    (nums.drop i).take (j - i + 1);

  let distinctCount_local := fun (l : List Nat) =>
    let foldFn := fun (seen : List Nat) (x : Nat) =>
      if seen.elem x then seen else x :: seen;
    let distinctElems := l.foldl foldFn [];
    distinctElems.length;

  let square_local := fun (n : Nat) => n * n;

  (1 <= n ∧ n <= 100 ∧ nums.all (fun x => 1 <= x ∧ x <= 100)) ->
  (
    result >= 0
    ∧
    let expectedSum : Nat :=
      List.range n |>.foldl (fun (outerSum : Nat) (i : Nat) =>
        let innerSum : Nat :=
          List.range (n - i) |>.foldl (fun (currentInnerSum : Nat) (d : Nat) =>
            let j := i + d;
            let subarr := getSubarray_local i j;
            let count := distinctCount_local subarr;
            currentInnerSum + square_local count
          ) 0
        outerSum + innerSum
      ) 0;

    result = expectedSum
  )

theorem solution_spec_satisfied (nums: List Nat) :
    solution_postcond (nums) (solution (nums)) := by
  -- By definition of `solution`, we know that it satisfies the postcondition.
  simp [solution_postcond, solution];
  -- By definition of `distinctCount`, we know that it correctly computes the number of distinct elements in a list.
  have h_distinctCount : ∀ (l : List ℕ), (List.foldl (fun (s : Std.HashSet ℕ) (a : ℕ) => s.insert a) Std.HashSet.empty l).size = (List.foldl (fun (seen : List ℕ) (x : ℕ) => if x ∈ seen then seen else x :: seen) [] l).length := by
    intro l;
    induction' l using List.reverseRecOn with l ih;
    · rfl;
    · by_cases h : ih ∈ List.foldl ( fun seen x => if x ∈ seen then seen else x :: seen ) [ ] l <;> simp_all +decide [ Std.HashSet.size_insert ];
      · -- By definition of `foldl`, if `ih` is in the list after folding, then it must have been inserted into the set during the folding process.
        have h_insert : ∀ (l : List ℕ) (ih : ℕ), ih ∈ List.foldl (fun (seen : List ℕ) (x : ℕ) => if x ∈ seen then seen else x :: seen) [] l → ih ∈ List.foldl (fun (s : Std.HashSet ℕ) (a : ℕ) => s.insert a) Std.HashSet.empty l := by
          intros l ih h; induction' l using List.reverseRecOn with l ih <;> aesop;
        exact h_insert l ih h;
      · contrapose! h;
        have h_ind : ∀ (l : List ℕ), ∀ (x : ℕ), x ∈ List.foldl (fun (s : Std.HashSet ℕ) (a : ℕ) => s.insert a) Std.HashSet.empty l → x ∈ List.foldl (fun (seen : List ℕ) (x : ℕ) => if x ∈ seen then seen else x :: seen) [] l := by
          intros l x hx; induction' l using List.reverseRecOn with l ih <;> aesop;
        exact h_ind l ih h;
  grind
