/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 4c021037-a7dd-4273-9426-2b20b3449410

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
This module implements a function `palindromeIgnoreNonAlnum` that checks if a string is a palindrome, ignoring non-alphanumeric characters and case. It also includes a formal verification of this function, proving that it satisfies the postcondition `palindromeIgnoreNonAlnum_postcond` which states that the function returns true if and only if the cleaned string is equal to its reverse. The proof involves several helper lemmas relating the recursive check function to a range-based palindrome definition and finally to the list reversal property.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

@[reducible]
def palindromeIgnoreNonAlnum_precond (s : String) : Prop :=
  True

def palindromeIgnoreNonAlnum (s : String) (h_precond : palindromeIgnoreNonAlnum_precond (s)) : Bool :=
  let cleaned : List Char :=
    s.data.filter (fun c => c.isAlpha || c.isDigit)
      |>.map Char.toLower

  let n := cleaned.length
  let startIndex := 0
  let endIndex := if n = 0 then 0 else n - 1

  let rec check (l r : Nat) : Bool :=
    if l >= r then
      true
    else if cleaned[l]? = cleaned[r]? then
      check (l + 1) (r - 1)
    else
      false
    termination_by r - l

  check startIndex endIndex

@[reducible]
def palindromeIgnoreNonAlnum_postcond (s : String) (result: Bool) (h_precond : palindromeIgnoreNonAlnum_precond (s)) : Prop :=
  let cleaned := s.data.filter (fun c => c.isAlpha || c.isDigit) |>.map Char.toLower
  let forward := cleaned
  let backward := cleaned.reverse

  if result then
    forward = backward
  else
    forward ≠ backward

def check_aux (L : List Char) (l r : Nat) : Bool :=
  if l >= r then
    true
  else if L[l]? = L[r]? then
    check_aux L (l + 1) (r - 1)
  else
    false
termination_by r - l

def listSlice {α : Type} (L : List α) (l r : Nat) : List α :=
  (L.drop l).take (r - l + 1)

def IsPalindromeRange (L : List Char) (l r : Nat) : Prop :=
  ∀ k, l + k ≤ r - k → L[l+k]? = L[r-k]?

theorem check_aux_iff_IsPalindromeRange (L : List Char) (l r : Nat) :
    check_aux L l r = true ↔ IsPalindromeRange L l r := by
  -- By definition of `check_aux`, we know that `check_aux L l r` is true if and only if for all `k` such that `l + k ≤ r - k`, `L[l + k]? = L[r - k]?`. This follows directly from the recursive definition of `check_aux`.
  have h_check_aux_equiv : ∀ l r, check_aux L l r = Bool.true ↔ (∀ k, l + k ≤ r - k → L[l + k]? = L[r - k]?) := by
    -- We'll use induction on the difference between r and l.
    intro l r
    induction' h : r - l using Nat.strong_induction_on with d hd generalizing l r;
    unfold check_aux;
    split_ifs <;> simp_all +decide;
    · grind;
    · convert hd ( r - 1 - ( l + 1 ) ) _ ( l + 1 ) ( r - 1 ) rfl using 1;
      · -- The two conditions are equivalent because they are just shifted versions of each other.
        apply Iff.intro;
        · grind;
        · intro h k hk; specialize h ( k - 1 ) ; rcases k with ( _ | k ) <;> simp_all +decide [ Nat.sub_sub ] ;
          convert h ( by omega ) using 1 <;> ring;
      · omega;
    · exact ⟨ 0, by omega, by simpa using ‹¬L[l]? = L[r]?› ⟩;
  exact h_check_aux_equiv l r

theorem IsPalindromeRange_whole_list_iff (L : List Char) :
    IsPalindromeRange L 0 (if L.length = 0 then 0 else L.length - 1) ↔ L = L.reverse := by
  -- By definition of `IsPalindromeRange`, we know that `IsPalindromeRange L 0 (L.length - 1)` holds if and only if `L` is a palindrome. This follows directly from the definition of `IsPalindromeRange`.
  apply Iff.intro
  intro h_palindrome_range
  exact (by
  -- By definition of `IsPalindromeRange`, we know that `L[i] = L[j]` for all `i ≤ j` where `i + j = L.length - 1`.
  have h_symm : ∀ i j, i + j = L.length - 1 → L[i]? = L[j]? := by
    -- By definition of `IsPalindromeRange`, we know that for any `k`, if `k ≤ L.length - 1 - k`, then `L[k]? = L[L.length - 1 - k]?`.
    have h_symm : ∀ k, k ≤ L.length - 1 - k → L[k]? = L[L.length - 1 - k]? := by
      intro k hk; specialize h_palindrome_range k; aesop;
    intro i j hij
    by_cases h_cases : i ≤ j;
    · rw [ h_symm i ( by omega ), show L.length - 1 - i = j by omega ];
    · convert h_symm j ( by omega ) |> Eq.symm using 1 ; rw [ show i = L.length - 1 - j by omega ];
  -- By definition of `List.reverse`, we know that `L.reverse[i]? = L[L.length - 1 - i]?` for all `i`.
  have h_reverse : ∀ i, i < L.length → L.reverse[i]? = L[L.length - 1 - i]? := by
    grind
  generalize_proofs at *; (
  -- By combining the results from h_symm and h_reverse, we can conclude that L[i]? = L.reverse[i]? for all i < L.length.
  have h_eq : ∀ i < L.length, L[i]? = L.reverse[i]? := by
    exact fun i hi => by rw [ h_reverse i hi, h_symm i ( L.length - 1 - i ) ( by omega ) ] ;
  generalize_proofs at *; (
  refine' List.ext_get _ _ <;> aesop ( simp_config := { singlePass := true } ) ;)))
  intro h_palindrome
  exact (by
  intro k hk; replace h_palindrome := congr_arg ( fun L => L.get? k ) h_palindrome; rcases L with ( _ | ⟨ x, _ | ⟨ y, L ⟩ ⟩ ) <;> norm_num at *;
  · aesop;
  · grind)

def cleanString (s : String) : List Char :=
  s.data.filter (fun c => c.isAlpha || c.isDigit)
    |>.map Char.toLower

theorem palindromeIgnoreNonAlnum_eq_check_aux (s : String) (h : palindromeIgnoreNonAlnum_precond s) :
    palindromeIgnoreNonAlnum s h = check_aux (cleanString s) 0 (if (cleanString s).length = 0 then 0 else (cleanString s).length - 1) := by
  -- By definition of `check`, we know that it is equivalent to `check_aux` when applied to the same list and indices.
  have h_check_eq : ∀ (L : List Char) (l r : Nat), palindromeIgnoreNonAlnum.check L l r = check_aux L l r := by
    -- By definition of `palindromeIgnoreNonAlnum.check`, we know that it is equivalent to `check_aux` when applied to the same list and indices.
    intros L l r
    induction' h : r - l using Nat.strong_induction_on with n ih generalizing l r;
    unfold palindromeIgnoreNonAlnum.check check_aux;
    grind;
  apply h_check_eq _ _

theorem palindromeIgnoreNonAlnum_spec_satisfied (s: String) (h_precond : palindromeIgnoreNonAlnum_precond (s)) :
    palindromeIgnoreNonAlnum_postcond (s) (palindromeIgnoreNonAlnum (s) h_precond) h_precond := by
  convert IsPalindromeRange_whole_list_iff ( cleanString s ) using 1;
  rw [ palindromeIgnoreNonAlnum_eq_check_aux ];
  unfold palindromeIgnoreNonAlnum_postcond;
  simp +decide [ check_aux_iff_IsPalindromeRange ];
  split_ifs <;> simp_all +decide [ cleanString ]
