/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 645960f6-2857-4684-83f1-7d12085b2267

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
This module defines a function `smallestMissing` that finds the smallest missing natural number in a sorted list of natural numbers.
It also defines the precondition `smallestMissing_precond` (the list is sorted) and the postcondition `smallestMissing_postcond` (the result is not in the list, and all smaller natural numbers are in the list).
Finally, it proves `smallestMissing_spec_satisfied`, which states that `smallestMissing` satisfies the postcondition given the precondition.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

@[reducible]
def smallestMissing_precond (l : List Nat) : Prop :=
  List.Pairwise (· < ·) l

def smallestMissing (l : List Nat) (h_precond : smallestMissing_precond (l)) : Nat :=
  let sortedList := l
  let rec search (lst : List Nat) (n : Nat) : Nat :=
    match lst with
    | [] => n
    | x :: xs =>
      let isEqual := x = n
      let isGreater := x > n
      let nextCand := n + 1
      if isEqual then
        search xs nextCand
      else if isGreater then
        n
      else
        search xs n
  let result := search sortedList 0
  result

@[reducible]
def smallestMissing_postcond (l : List Nat) (result: Nat) (h_precond : smallestMissing_precond (l)) : Prop :=
  result ∉ l ∧ ∀ candidate : Nat, candidate < result → candidate ∈ l

theorem smallestMissing_spec_satisfied (l: List Nat) (h_precond : smallestMissing_precond (l)) :
    smallestMissing_postcond (l) (smallestMissing (l) h_precond) h_precond := by
  -- By definition of `smallestMissing.search`, we know that it returns the smallest natural number not in `l`.
  have h_search : ∀ (l : List ℕ) (n : ℕ), smallestMissing_precond l → smallestMissing.search l n ∉ l ∧ ∀ candidate < smallestMissing.search l n, n ≤ candidate → candidate ∈ l := by
    intros l n h_precond
    induction' l with hd tl ih generalizing n;
    · -- In the base case, when the list is empty, the smallest missing natural number is 0.
      simp [smallestMissing.search];
    · -- By definition of `smallestMissing.search`, we know that it returns the smallest natural number not in `l` and for all smaller candidates, they are in `l`.
      simp [smallestMissing.search];
      split_ifs <;> simp_all +decide [ smallestMissing_precond ];
      · constructor;
        · -- By definition of `smallestMissing.search`, we know that it returns the smallest natural number not in `tl`.
          have h_search_tl : ∀ (l : List ℕ) (n : ℕ), smallestMissing_precond l → smallestMissing.search l n ≥ n := by
            intros l n h_precond; induction' l with hd tl ih generalizing n; simp [smallestMissing.search];
            simp [smallestMissing.search];
            split_ifs <;> simp_all +decide [ smallestMissing_precond ];
            -- By definition of `smallestMissing.search`, we know that it returns the smallest natural number not in `tl` and for all smaller candidates, they are in `tl`.
            have h_search_tl : ∀ (l : List ℕ) (n : ℕ), smallestMissing_precond l → smallestMissing.search l n ≥ n := by
              intros l n h_precond; induction' l with hd tl ih generalizing n; simp [smallestMissing.search];
              simp [smallestMissing.search];
              grind;
            exact le_trans ( by linarith ) ( h_search_tl _ _ h_precond.2 );
          linarith [ h_search_tl tl ( n + 1 ) h_precond.2 ];
        · grind;
      · exact ⟨ Ne.symm ‹_›, fun h => by linarith [ h_precond.1 _ h ] ⟩;
      · -- Since $hd < n$ and $hd \leq n$, we have $hd < n$.
        have h_hd_lt_n : hd < n := by
          exact lt_of_le_of_ne ‹_› ‹_›;
        -- Since $hd < n$ and $hd \leq n$, we have $hd < n$. Therefore, $smallestMissing.search tl n$ cannot be equal to $hd$.
        have h_neq : smallestMissing.search tl n ≠ hd := by
          have h_neq : ∀ (tl : List ℕ) (n : ℕ), smallestMissing_precond tl → n ≤ smallestMissing.search tl n := by
            intros tl n h_precond; induction' tl with hd tl ih generalizing n; simp [smallestMissing.search]; (
            simp [smallestMissing.search];
            grind);
          exact ne_of_gt ( lt_of_lt_of_le h_hd_lt_n ( h_neq tl n h_precond.2 ) );
        exact ⟨ h_neq, fun candidate h₁ h₂ => Or.inr <| ih _ _ h₁ h₂ ⟩;
  exact ⟨ h_search l 0 h_precond |>.1, fun candidate hc => h_search l 0 h_precond |>.2 candidate hc ( Nat.zero_le _ ) ⟩
