/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 4caf9f2b-dbef-4d66-bcef-cdb1b79874d7

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
This module implements a function `moveZeroes` that moves all zeroes in a list of integers to the end while preserving the relative order of non-zero elements. It also includes a proof `moveZeroes_spec_satisfied` that verifies the correctness of the implementation against the specified postconditions:
1. Non-zero elements maintain their relative order.
2. All zeroes are at the end of the list.
3. The number of zeroes and total elements remains unchanged.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

@[reducible]
def moveZeroes_precond (xs : List Int) : Prop :=
  True

def moveZeroes (xs : List Int) (h_precond : moveZeroes_precond (xs)) : List Int :=
  let nonzeros := xs.filter (fun x => x ≠ 0)
  let zeros := xs.filter (fun x => x = 0)
  nonzeros ++ zeros

def countVal (val : Int) : List Int → Nat
  | [] => 0
  | x :: xs =>
    let rest := countVal val xs
    if x = val then rest + 1 else rest

-- Check whether one list is a subsequence of another (preserving relative order)
def isSubsequence (xs ys : List Int) : Bool :=
  match xs, ys with
  | [], _ => true
  | _ :: _, [] => false
  | x :: xt, y :: yt =>
    if x = y then isSubsequence xt yt else isSubsequence xs yt

@[reducible]
def moveZeroes_postcond (xs : List Int) (result: List Int) (h_precond : moveZeroes_precond (xs)) : Prop :=
  -- 1. All non-zero elements must maintain their relative order
  isSubsequence (xs.filter (fun x => x ≠ 0)) result = true ∧

  -- 2. All zeroes must be located at the end of the output list
  (result.dropWhile (fun x => x ≠ 0)).all (fun x => x = 0) ∧

  -- 3. The output must contain the same number of elements,
  --    and the number of zeroes must remain unchanged
  countVal 0 xs = countVal 0 result ∧
  xs.length = result.length

theorem moveZeroes_spec_satisfied (xs: List Int) (h_precond : moveZeroes_precond (xs)) :
    moveZeroes_postcond (xs) (moveZeroes (xs) h_precond) h_precond := by
  -- Let's unfold the definition of `moveZeroes_postcond`.
  simp [moveZeroes_postcond];
  refine' ⟨ _, _, _, _ ⟩;
  · -- By definition of `moveZeroes`, the non-zero elements of `xs` are preserved in the result.
    simp [moveZeroes];
    -- The first part of the conjunction is trivially true since any list is a subsequence of itself.
    induction' (List.filter (fun x => !Decidable.decide (x = 0)) xs) with x xs ih;
    · induction ( List.filter ( fun x => Decidable.decide ( x = 0 ) ) xs ) <;> aesop;
    · exact by rw [ show isSubsequence ( x :: xs ) ( x :: xs ++ List.filter ( fun x => Decidable.decide ( x = 0 ) ) _ ) = isSubsequence xs ( xs ++ List.filter ( fun x => Decidable.decide ( x = 0 ) ) _ ) from by { exact if_pos ( rfl ) } ] ; assumption;
  · intro x hx
    unfold moveZeroes at hx
    simp at *;
    -- Since `x` is in the list obtained by dropping elements from the filtered list where elements are zero, and the filtered list contains only zeros, `x` must be zero.
    have h_filter_zero : ∀ x ∈ List.filter (fun x => x = 0) xs, x = 0 := by
      grind;
    have h_dropWhile_zero : ∀ {l : List ℤ}, (∀ x ∈ l, x = 0) → ∀ x ∈ List.dropWhile (fun x => !Decidable.decide (x = 0)) l, x = 0 := by
      intros l hl x hx; induction l <;> aesop;
    exact h_dropWhile_zero h_filter_zero x hx;
  · unfold moveZeroes;
    -- By definition of `countVal`, we can split the count into the sum of counts in the nonzeros and zeros lists.
    have h_split : ∀ (xs : List ℤ), countVal 0 xs = List.countP (fun x => x = 0) xs := by
      intro xs; induction xs <;> simp +decide [ *, countVal ] ;
      split_ifs <;> simp +decide [ *, List.countP_cons ];
    simp +decide [ h_split, List.countP_eq_length_filter ];
  · -- By definition of `moveZeroes`, we have `moveZeroes xs h_precond = nonzeros ++ zeros`.
    simp [moveZeroes];
    rw [ List.length_eq_countP_add_countP ];
    congr! 1;
    all_goals rw [ List.countP_eq_length_filter ];
    grind
