/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 7ab65f4b-a74b-4c34-8750-b0d8cfc558cb

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
This module defines a function `reverseWords` that reverses the order of words in a given string, removing extra spaces. It also includes a formal specification `reverseWords_postcond` and a proof `reverseWords_spec_satisfied` that the function satisfies this specification.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

@[reducible]
def reverseWords_precond (words_str : String) : Prop :=
  True

def reverseWords (words_str : String) (h_precond : reverseWords_precond (words_str)) : String :=
  let rawWords : List String := words_str.splitOn " "
  let rec filterNonEmpty (words : List String) : List String :=
    match words with
    | [] => []
    | h :: t =>
      if h = "" then
        filterNonEmpty t
      else
        h :: filterNonEmpty t
  let filteredWords : List String := filterNonEmpty rawWords
  let revWords : List String := filteredWords.reverse
  let rec joinWithSpace (words : List String) : String :=
    match words with
    | [] => ""
    | [w] => w
    | h :: t =>
      h ++ " " ++ joinWithSpace t
  let result : String := joinWithSpace revWords
  result

@[reducible]
def reverseWords_postcond (words_str : String) (result: String) (h_precond : reverseWords_precond (words_str)) : Prop :=
  ∃ words : List String,
    (words = (words_str.splitOn " ").filter (fun w => w ≠ "")) ∧
    result = String.intercalate " " (words.reverse)

theorem reverseWords_spec_satisfied (words_str: String) (h_precond : reverseWords_precond (words_str)) :
    reverseWords_postcond (words_str) (reverseWords (words_str) h_precond) h_precond := by
  -- By definition of `joinWithSpace`, we know that `joinWithSpace (filterNonEmpty (splitOn words_str))` is equal to `intercalate " " (filterNonEmpty (splitOn words_str))`.
  have h_join : ∀ (words : List String), reverseWords.joinWithSpace words = String.intercalate " " words := by
    -- By definition of `joinWithSpace`, we can show that it is equivalent to `String.intercalate` by induction on the list of words.
    intro words
    induction' words with w words ih;
    · rfl;
    · induction' words with w' words' ih' <;> simp_all +decide [ reverseWords.joinWithSpace ];
      · exact?;
      · -- By definition of `intercalate`, we can split the list into the first element and the rest.
        have h_intercalate_split : ∀ (w : String) (ws : List String), String.intercalate " " (w :: ws) = w ++ List.foldr (fun s acc => " " ++ s ++ acc) "" ws := by
          intros w ws; induction ws generalizing w <;> simp +decide [ *, String.intercalate ] ;
          · rfl;
          · rename_i k hk ih; specialize ih ( w ++ " " ++ k ) ; simp_all +decide [ String.intercalate ] ;
            convert ih using 1;
            simp +decide [ String.ext_iff, List.foldr ];
        simp +decide [ h_intercalate_split, String.ext_iff ];
  -- By definition of `filterNonEmpty`, we know that `filterNonEmpty (splitOn words_str)` is equal to `filter (fun w => w ≠ "") (splitOn words_str)`.
  have h_filter : ∀ (words : List String), reverseWords.filterNonEmpty words = List.filter (fun w => w ≠ "") words := by
    -- By definition of `filterNonEmpty`, we know that it is equivalent to the standard filter function with the condition `fun w => w ≠ ""`.
    intros words
    induction' words with w ws ih;
    · rfl;
    · by_cases h : w = "" <;> simp +decide [ h, ih, reverseWords.filterNonEmpty ];
  unfold reverseWords; aesop;
