/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 7828ceeb-046d-4e8f-a535-bcfd3f41c735

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
We define a function `uniqueSorted` that takes a list of integers, removes duplicates, and sorts the result. We then prove that this function satisfies the postcondition that the result is a permutation of the input with duplicates removed and is sorted.
-/
import Codetic
import Mathlib
-- set_option trace.codetic true
-- set_option trace.codetic.zzh_custom true
set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

@[reducible, simp] def uniqueSorted_precond (arr : List Int) : Prop := True

/-
The postcondition states that the result is a permutation of the input with duplicates removed, and the result is sorted.
-/
@[reducible, simp] def uniqueSorted_postcond (arr : List Int) (result: List Int) (h_precond : uniqueSorted_precond (arr)) : Prop :=
  List.Perm arr.eraseDups result ∧ List.Pairwise (· ≤ ·) result

def uniqueSorted (arr : List Int) (h_precond : uniqueSorted_precond (arr)) : List Int :=
  let rec insert (x : Int) (sorted : List Int) : List Int :=
    match sorted with
    | [] => [x]
    | head :: tail =>
      if x <= head then x :: head :: tail
      else head :: insert x tail
  let rec insertionSort (xs : List Int) : List Int :=
    match xs with
    | [] => []
    | h :: t =>
      let sortedTail := insertionSort t
      insert h sortedTail
  let removeDups := fun (xs : List Int) =>
    let rec aux (remaining : List Int) (seen : List Int) (acc : List Int) : List Int :=
      match remaining with
      | [] => acc.reverse
      | h :: t =>
        if h ∈ seen then aux t seen acc
        else aux t (h :: seen) (h :: acc)
    aux xs [] []
  insertionSort (removeDups arr)

theorem uniqueSorted_spec_satisfied (arr: List Int) (h_precond : uniqueSorted_precond (arr)) :
  uniqueSorted_postcond (arr) (uniqueSorted (arr) h_precond) h_precond := by
    -- By definition of `uniqueSorted`, we know that the result is a permutation of the input with duplicates removed and sorted.
    have h_perm : List.Perm (List.eraseDups arr) (uniqueSorted arr h_precond) := by
      -- By definition of `insert`, we know that inserting an element into a list preserves the permutation property.
      have h_insert_perm : ∀ (x : ℤ) (l : List ℤ), List.Perm (x :: l) (uniqueSorted.insert x l) := by
        -- We can prove this by induction on the list `l`.
        intro x l
        induction' l with y l ih;
        · -- In the base case, when the list is empty, inserting x results in [x], which is a permutation of [x].
          simp [uniqueSorted.insert];
        · by_cases h : x ≤ y <;> simp_all +decide [ uniqueSorted.insert ];
          rw [ if_neg h.not_le ] ; exact List.Perm.trans ( List.Perm.swap .. ) ( List.Perm.cons _ ih ) ;
      -- By definition of `insertionSort`, we know that inserting elements into a list preserves the permutation property.
      have h_insertionSort_perm : ∀ (l : List ℤ), List.Perm l (uniqueSorted.insertionSort l) := by
        intro l; induction' l with x l ih; aesop;
        convert List.Perm.trans ( List.Perm.cons _ ih ) ( h_insert_perm _ _ ) using 1;
      -- By definition of `uniqueSorted`, we know that `uniqueSorted arr h_precond` is the insertion sort of the list obtained by removing duplicates from `arr`.
      simp [uniqueSorted];
      -- By definition of `uniqueSorted.aux`, we know that `uniqueSorted.aux arr [] []` is the list obtained by removing duplicates from `arr`.
      have h_aux_eq_eraseDups : ∀ (l : List ℤ) (seen : List ℤ) (acc : List ℤ), uniqueSorted.aux l seen acc = acc.reverse ++ (l.filter (fun x => x ∉ seen)).eraseDups := by
        intros l seen acc; induction' l with x l ih generalizing seen acc <;> simp_all +decide [ List.eraseDups_cons ] ;
        · -- By definition of `uniqueSorted.aux`, when the remaining list is empty, it returns the accumulator reversed.
          simp [uniqueSorted.aux];
        · by_cases hx : x ∈ seen <;> simp_all +decide [ List.filter_cons ];
          · convert ih seen acc using 1;
            exact if_pos hx;
          · convert ih ( x :: seen ) ( x :: acc ) using 1;
            · exact if_neg hx;
            · simp +decide [ hx, List.eraseDups_cons ];
              grind;
      aesop;
    -- By definition of `insert`, we know that inserting an element into a sorted list maintains the sorted property.
    have h_insert_sorted (x : ℤ) (sorted : List ℤ) (h_sorted : List.Pairwise (· ≤ ·) sorted) : List.Pairwise (· ≤ ·) (uniqueSorted.insert x sorted) := by
      -- By definition of `insert`, we know that inserting an element into a sorted list maintains the sorted property. We can prove this by induction on the sorted list.
      induction' sorted with y sorted ih;
      · exact List.pairwise_singleton _ _;
      · by_cases hxy : x ≤ y <;> simp_all +decide [ uniqueSorted.insert ];
        · exact fun a ha => le_trans hxy ( h_sorted.1 a ha );
        · split_ifs <;> simp_all +decide [ List.pairwise_cons ];
          · linarith;
          · intro a' ha'; induction' sorted with y sorted ih generalizing x <;> simp_all +decide [ uniqueSorted.insert ] ;
            · linarith;
            · grind;
    -- By definition of `insertionSort`, we know that the result is a sorted permutation of the input.
    have h_insertionSort_sorted (xs : List ℤ) : List.Pairwise (· ≤ ·) (uniqueSorted.insertionSort xs) := by
      -- By induction on the list, we can show that the insertion sort of any list is sorted.
      -- induction' xs with x xs ih;
      -- · trivial;
      -- · exact h_insert_sorted x _ ih;
      induction xs

      codetic?
      exact List.pwFilter_eq_self.mp rfl
      apply h_insert_sorted
      simp_all only

    exact ⟨ h_perm, h_insertionSort_sorted _ ⟩
