/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 070d0f0f-cd9b-476a-97cd-dd72ebb1e7b8

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
We define `shortestBeautifulSubstring` which finds the shortest substring of a binary string `s` containing exactly `k` ones. If there are multiple such substrings of the same minimal length, it returns the lexicographically smallest one. We prove that this function satisfies the postcondition `shortestBeautifulSubstring_postcond`, meaning it returns a valid substring with the required properties, or the empty string if no such substring exists.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

def countOnes (lst : List Char) : Nat :=
  lst.foldl (fun acc c => if c = '1' then acc + 1 else acc) 0

@[reducible]
def shortestBeautifulSubstring_precond (s : String) (k : Nat) : Prop :=
  s.toList.all (fun c => c = '0' ∨ c = '1')

def listToString (lst : List Char) : String :=
  String.mk lst

def isLexSmaller (a b : List Char) : Bool :=
  listToString a < listToString b

def allSubstrings (s : List Char) : List (List Char) :=
  let n := s.length
  (List.range n).flatMap (fun i =>
    (List.range (n - i)).map (fun j =>
      s.drop i |>.take (j + 1)))

def shortestBeautifulSubstring (s : String) (k : Nat) (h_precond : shortestBeautifulSubstring_precond (s) (k)) : String :=
  let chars := s.data
  let candidates := allSubstrings chars |>.filter (fun sub => countOnes sub = k)

  let compare (a b : List Char) : Bool :=
    a.length < b.length ∨ (a.length = b.length ∧ isLexSmaller a b)

  let best := candidates.foldl (fun acc cur =>
    match acc with
    | none => some cur
    | some best => if compare cur best then some cur else some best) none
  match best with
  | some b => listToString b
  | none => ""

@[reducible]
def shortestBeautifulSubstring_postcond (s : String) (k : Nat) (result: String) (h_precond : shortestBeautifulSubstring_precond (s) (k)) : Prop :=
  let chars := s.data
  let substrings := (List.range chars.length).flatMap (fun i =>
    (List.range (chars.length - i + 1)).map (fun len =>
      chars.drop i |>.take len))
  let isBeautiful := fun sub => countOnes sub = k
  let beautiful := substrings.filter (fun sub => isBeautiful sub)
  let targets := beautiful.map (·.asString) |>.filter (fun s => s ≠ "")
  (result = "" ∧ targets = []) ∨
  (result ∈ targets ∧
   ∀ r ∈ targets, r.length ≥ result.length ∨ (r.length = result.length ∧ result ≤ r))

def compareCandidates (a b : List Char) : Bool :=
  a.length < b.length ∨ (a.length = b.length ∧ isLexSmaller a b)

def updateCandidate (acc : Option (List Char)) (cur : List Char) : Option (List Char) :=
  match acc with
  | none => some cur
  | some best => if compareCandidates cur best then some cur else some best

theorem shortestBeautifulSubstring_foldl_eq (l : List (List Char)) :
  l.foldl (fun acc cur =>
    match acc with
    | none => some cur
    | some best => if cur.length < best.length ∨ (cur.length = best.length ∧ isLexSmaller cur best) then some cur else some best) none
  = l.foldl updateCandidate none := by
    congr;
    -- By definition of `updateCandidate`, we can rewrite the goal using the match expression.
    funext acc cur; exact (by
    -- By definition of `updateCandidate`, we can rewrite the goal using the match expression. We'll split into cases based on whether `acc` is `none` or `some best`.
    cases acc <;> simp [updateCandidate];
    -- By definition of `compareCandidates`, we can rewrite the goal using the match expression. We'll split into cases based on whether `acc` is `none` or `some best` and simplify the if statement.
    simp [compareCandidates])

theorem foldl_updateCandidate_mem (l : List (List Char)) (best : List Char) :
  l.foldl updateCandidate none = some best → best ∈ l := by
    -- By definition of `updateCandidate`, if the foldl results in `some best`, then `best` must have been in the list `ih` because each step of the foldl adds the best candidate from the current list.
    have h_foldl : ∀ (acc : Option (List Char)) (l : List (List Char)), List.foldl updateCandidate acc l = some best → acc = some best ∨ best ∈ l := by
      -- By induction on the list l, we can show that if the foldl of updateCandidate on l with some x is some best, then x must be some best or best is in l.
      intro acc l h_foldl
      induction' l with l ih generalizing acc best <;> simp [updateCandidate] at *;
      · exact h_foldl;
      · cases acc <;> simp_all +decide [ updateCandidate ];
        · grind +ring;
        · grind;
    grind

theorem foldl_updateCandidate_optimal (l : List (List Char)) (best : List Char) :
  l.foldl updateCandidate none = some best → ∀ x ∈ l, compareCandidates x best = false := by
    intros h x hx;
    have h_foldl : ∀ (l : List (List Char)) (best : List Char), List.foldl updateCandidate none l = some best → ∀ x ∈ l, compareCandidates x best = Bool.false := by
      -- By induction on the list, we can show that if the foldl of updateCandidate on l is some best, then for any x in l, compareCandidates x best is false.
      intros l best h_foldl x hx
      induction' l using List.reverseRecOn with l ih generalizing best;
      · contradiction;
      · by_cases h : x ∈ l <;> simp_all +decide [ List.foldl_append ];
        · cases h' : List.foldl updateCandidate Option.none l <;> simp_all +decide [ updateCandidate ];
          · -- By induction on the list l, we can show that if the foldl of updateCandidate on l is none, then l must be empty.
            have h_empty : ∀ (l : List (List Char)), List.foldl updateCandidate Option.none l = Option.none → l = [] := by
              intros l hl; induction' l using List.reverseRecOn with l ih generalizing best; aesop;
              cases h : List.foldl updateCandidate Option.none l <;> simp_all +decide [ updateCandidate ];
              grind;
            specialize h_empty l h'; aesop;
          · split_ifs at h_foldl <;> simp_all +decide [ compareCandidates ];
            -- By combining the results from the induction hypothesis and the current case, we can conclude the proof.
            apply And.intro;
            · grind;
            · -- By combining the results from the induction hypothesis and the current case, we can conclude that if x.length equals best.length, then isLexSmaller x best is false.
              intros h_eq
              have h_lex : isLexSmaller x best = Bool.false := by
                cases ‹best.length < _ ∨ _› <;> simp_all +decide [ isLexSmaller ];
                · grind;
                · exact le_trans ( by tauto ) ( by tauto )
              exact h_lex;
        · -- By definition of updateCandidate, if updateCandidate (List.foldl updateCandidate Option.none l) ih = some best, then best is either ih or the result of folding l.
          have h_update : best = ih ∨ best = (List.foldl updateCandidate Option.none l).get! := by
            -- By definition of updateCandidate, if updateCandidate (List.foldl updateCandidate Option.none l) ih = some best, then best is either ih or the result of folding l. This follows directly from the definition of updateCandidate.
            have h_update : ∀ (acc : Option (List Char)) (cur : List Char), updateCandidate acc cur = some best → best = cur ∨ best = acc.get! := by
              unfold updateCandidate; aesop;
            exact h_update _ _ h_foldl;
          -- By definition of updateCandidate, if updateCandidate (List.foldl updateCandidate Option.none l) ih = some best, then best is either ih or the result of folding l. In both cases, compareCandidates ih best is false.
          cases h_update <;> simp_all +decide [ updateCandidate ];
          · unfold compareCandidates; simp +decide ;
            unfold isLexSmaller; simp +decide ;
          · cases h' : List.foldl updateCandidate Option.none l <;> simp_all +decide [ updateCandidate ];
            · native_decide +revert;
            · -- By definition of updateCandidate, if updateCandidate (List.foldl updateCandidate Option.none l) ih = some best, then best is either ih or the result of folding l. In both cases, compareCandidates ih best is false because if ih is equal to best, then compareCandidates ih best is false.
              by_contra h_contra;
              have := foldl_updateCandidate_mem l _ h'; aesop;
    exact h_foldl l best h x hx

theorem foldl_updateCandidate_none (l : List (List Char)) :
  l.foldl updateCandidate none = none ↔ l = [] := by
    -- We'll use induction on the list `l`.
    induction' l with x l ih ih;
    · exact?;
    · -- By definition of `updateCandidate`, if the list is non-empty, the foldl cannot be none.
      have h_nonempty : ∀ (l : List (List Char)), l ≠ [] → List.foldl updateCandidate none l ≠ none := by
        -- By induction on the list, we can show that if the list is non-empty, the foldl will process the first element and set the accumulator to that element, then process the rest of the list.
        intro l hl_nonempty
        induction' l with x l ih;
        · contradiction;
        · induction' l using List.reverseRecOn with x l ih <;> simp_all +decide [ List.foldl ];
          · exact?;
          · unfold updateCandidate; aesop;
      specialize h_nonempty ( x :: l ) ; aesop

def allSubstrings_spec (s : List Char) : List (List Char) :=
  (List.range s.length).flatMap (fun i =>
    (List.range (s.length - i + 1)).map (fun len =>
      s.drop i |>.take len))

theorem allSubstrings_eq_filter_spec (s : List Char) :
  allSubstrings s = (allSubstrings_spec s).filter (fun x => x ≠ []) := by
    -- By definition of `allSubstrings`, we know that it is equal to `allSubstrings_spec` filtered by non-empty sublists because `allSubstrings` includes only non-empty sublists.
    simp [allSubstrings, allSubstrings_spec];
    -- The two lists are equal because the flatMap of the first list already excludes the empty lists that are present in the second list.
    have h_eq : ∀ i ∈ List.range s.length, List.map (fun j => List.take (j + 1) (List.drop i s)) (List.range (s.length - i)) = List.filter (fun x => !Decidable.decide (x = [])) (List.map (fun len => List.take len (List.drop i s)) (List.range (s.length - i + 1))) := by
      intro i hi; induction s.length - i <;> simp_all +decide [ List.range_succ_eq_map ] ;
      rw [ List.filter_eq_self.mpr ] ; aesop;
      simp_all +decide [ Function.comp ];
    -- By applying h_eq to each element in the flatMap, we can replace each map with the filtered map.
    have h_flatMap_eq : List.flatMap (fun i => List.map (fun j => List.take (j + 1) (List.drop i s)) (List.range (s.length - i))) (List.range s.length) = List.flatMap (fun i => List.filter (fun x => !Decidable.decide (x = [])) (List.map (fun len => List.take len (List.drop i s)) (List.range (s.length - i + 1)))) (List.range s.length) := by
      exact?;
    exact h_flatMap_eq.trans ( by induction ( List.range s.length ) <;> aesop )

theorem compareCandidates_false_implies_le (a b : List Char) :
  compareCandidates a b = false → b.length < a.length ∨ (b.length = a.length ∧ listToString b ≤ listToString a) := by
    -- By definition of compareCandidates, if compareCandidates a b is false, then either a.length > b.length or a.length = b.length and a is not less than b lexicographically. This follows directly from the definition of compareCandidates.
    simp [compareCandidates];
    -- We can split into cases based on whether `b.length` is less than or equal to `a.length`.
    by_cases h : b.length < a.length;
    · grind;
    · -- Since $b.length$ is not less than $a.length$, we have $b.length \geq a.length$. If $b.length = a.length$, then by the definition of compareCandidates, $a$ is not less than $b$ lexicographically.
      by_cases h_eq : b.length = a.length;
      · -- Since $a$ is not less than $b$ lexicographically, we have $b \leq a$.
        have h_lex : isLexSmaller a b = Bool.false → listToString b ≤ listToString a := by
          -- By definition of `isLexSmaller`, if `isLexSmaller a b` is false, then `a` is not less than `b`, which means `b` is less than or equal to `a`.
          simp [isLexSmaller];
        aesop;
      · exact fun h' => False.elim <| h_eq <| le_antisymm h' <| le_of_not_gt h

theorem targets_eq_candidates (s : String) (k : Nat) :
  let chars := s.data
  let candidates := allSubstrings chars |>.filter (fun sub => countOnes sub = k)
  let substrings := (List.range chars.length).flatMap (fun i =>
    (List.range (chars.length - i + 1)).map (fun len =>
      chars.drop i |>.take len))
  let beautiful := substrings.filter (fun sub => countOnes sub = k)
  let targets := beautiful.map (String.mk) |>.filter (fun s => s ≠ "")
  targets = candidates.map String.mk := by
    -- By definition of `allSubstrings`, we can rewrite the goal using `allSubstrings_spec`.
    have h_allSubstrings_eq : allSubstrings s.data = (allSubstrings_spec s.data).filter (fun x => x ≠ []) := by
      exact?;
    -- By definition of `allSubstrings`, we can rewrite the goal using `allSubstrings_spec` and the fact that filtering for non-empty substrings does not change the list.
    simp [h_allSubstrings_eq, List.filter_filter];
    -- By definition of `allSubstrings_spec`, we can rewrite the goal using `allSubstrings_spec` and the fact that filtering for non-empty substrings does not change the list.
    simp [allSubstrings_spec];
    -- By definition of `List.filter`, we can rewrite the left-hand side to match the right-hand side.
    simp [List.filter_map];
    simp +decide [ String.ext_iff ];
    grind

theorem shortestBeautifulSubstring_spec_satisfied (s: String) (k: Nat) (h_precond : shortestBeautifulSubstring_precond (s) (k)) :
    shortestBeautifulSubstring_postcond (s) (k) (shortestBeautifulSubstring (s) (k) h_precond) h_precond := by
  -- Let's unfold the definition of `shortestBeautifulSubstring` and `shortestBeautifulSubstring_postcond`.
  unfold shortestBeautifulSubstring shortestBeautifulSubstring_postcond;
  field_simp;
  rcases h : List.foldl _ Option.none ( List.filter ( fun sub => Decidable.decide ( countOnes sub = k ) ) ( allSubstrings s.data ) ) with ( _ | b ) <;> simp +decide [ h ];
  · -- By definition of `foldl`, if the result is `none`, then the list of candidates is empty.
    have h_empty : List.filter (fun sub => countOnes sub = k) (allSubstrings s.data) = [] := by
      convert foldl_updateCandidate_none _ |>.1 h;
    unfold allSubstrings at h_empty; simp_all +decide [ List.filter_eq ] ;
    intro a x y hy z hz hx hk ha; specialize h_empty x y hy ( z - 1 ) ; rcases z <;> aesop;
  · -- By definition of `foldl`, we know that `b` is the optimal candidate.
    have h_optimal : b ∈ (List.filter (fun sub => countOnes sub = k) (allSubstrings s.data)) ∧ ∀ x ∈ (List.filter (fun sub => countOnes sub = k) (allSubstrings s.data)), compareCandidates x b = false := by
      apply And.intro;
      · exact?;
      · exact?;
    -- By definition of `foldl`, we know that `b` is the optimal candidate, so we can split into the two cases.
    right
    constructor;
    · unfold allSubstrings at h_optimal; simp_all +decide [ List.mem_filter ] ;
      refine' ⟨ _, _ ⟩;
      · use b;
        exact ⟨ ⟨ by obtain ⟨ ⟨ a, ha, b, hb, rfl ⟩, hk ⟩ := h_optimal.1; exact ⟨ a, ha, b + 1, by linarith, by simp +decide ⟩, h_optimal.1.2 ⟩, rfl ⟩;
      · rcases h_optimal.1.1 with ⟨ a, ha, b, hb, rfl ⟩ ; simp +decide [ listToString ];
        rw [ String.ext_iff ] ; aesop;
    · intros r x i hi j hj hx hk hr hr'; subst_vars; simp_all +decide [ List.asString ] ;
      have := h_optimal.2 ( List.take j ( List.drop i s.data ) ) ?_ ?_ <;> simp_all +decide [ compareCandidates ];
      · exact Or.inl ⟨ this.1.1, this.1.2 ⟩;
      · unfold allSubstrings; simp +decide [ List.mem_flatMap, List.mem_map ] ;
        exact ⟨ i, hi, j - 1, by omega, by cases j <;> aesop ⟩
