/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 697a2383-3015-48ae-9210-919f7d72095a

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
We have defined the function `productExceptSelf` which computes the product of all elements in a list except the one at the current index, for each index. We have also defined the necessary helper functions `computepref` and `computeSuffix` to achieve O(n) time complexity. Finally, we have formally proven that `productExceptSelf` satisfies the specification given by `productExceptSelf_postcond`, which states that the output list contains the correct products.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

@[reducible]
def productExceptSelf_precond (nums : List Int) : Prop :=
  True

-- Helper: Compute prefix products.
-- prefix[i] is the product of all elements in nums before index i.
def computepref (nums : List Int) : List Int :=
  nums.foldl (fun acc x => acc ++ [acc.getLast! * x]) [1]

-- Helper: Compute suffix products.
-- suffix[i] is the product of all elements in nums from index i (inclusive) to the end.
-- We reverse the list and fold, then reverse back.
def computeSuffix (nums : List Int) : List Int :=
  let revSuffix := nums.reverse.foldl (fun acc x => acc ++ [acc.getLast! * x]) [1]
  revSuffix.reverse

def productExceptSelf (nums : List Int) (h_precond : productExceptSelf_precond (nums)) : List Int :=
  let n := nums.length
  if n = 0 then []
  else
    let pref := computepref nums
    let suffix := computeSuffix nums
    List.range n |>.map (fun i => pref[i]! * suffix[i+1]!)

-- Specification Helper: Product of a list of Ints
-- Defined locally if not available/imported
def List.myprod : List Int → Int
  | [] => 1
  | x :: xs => x * xs.myprod

@[reducible]
def productExceptSelf_postcond (nums : List Int) (result: List Int) (h_precond : productExceptSelf_precond (nums)) : Prop :=
  nums.length = result.length ∧
  (List.range nums.length |>.all (fun i =>
    result[i]! = some (((List.take i nums).myprod) * ((List.drop (i+1) nums).myprod))))

theorem productExceptSelf_spec_satisfied (nums: List Int) (h_precond : productExceptSelf_precond (nums)) :
    productExceptSelf_postcond (nums) (productExceptSelf (nums) h_precond) h_precond := by
  -- By definition of prefix and suffix products, we can show that their product at each index gives the desired result.
  have h_prefix_suffix : ∀ i ∈ List.range nums.length, (List.take i nums).myprod * (List.drop (i + 1) nums).myprod = (List.foldl (fun acc x => acc ++ [acc.getLast! * x]) [1] (List.take i nums)).getLast! * (List.foldl (fun acc x => acc ++ [acc.getLast! * x]) [1] (List.reverse (List.drop (i + 1) nums))).getLast! := by
    -- By definition of `List.foldl`, we can show that the last element of the list obtained by folding the take i of nums is indeed the product of the elements in take i nums.
    have h_prefix : ∀ (l : List ℤ), (List.foldl (fun acc x => acc ++ [acc.getLast! * x]) [1] l).getLast! = l.myprod := by
      -- We can prove this by induction on the list `l`.
      intro l
      induction' l using List.reverseRecOn with l ih;
      · rfl;
      · simp_all +decide [ List.myprod ];
        -- By definition of `List.myprod`, we know that `List.myprod (l ++ [ih]) = List.myprod l * ih`.
        have h_myprod_append : ∀ (l : List ℤ) (ih : ℤ), List.myprod (l ++ [ih]) = List.myprod l * ih := by
          intros l ih; induction l <;> simp_all +decide [ List.myprod ] ;
          ring;
        rw [ h_myprod_append ];
    -- By definition of `List.foldl`, we can show that the last element of the list obtained by folding the reverse drop of (i+1) nums is indeed the product of the elements in drop (i+1) nums.
    have h_suffix : ∀ (l : List ℤ), (List.foldl (fun acc x => acc ++ [acc.getLast! * x]) [1] (List.reverse l)).getLast! = l.myprod := by
      intro l; induction l <;> simp_all +decide [ List.myprod ] ;
      grind;
    grind;
  -- By combining the results from h_prefix_suffix and the definition of productExceptSelf, we can conclude that the productExceptSelf function satisfies the postcondition.
  have h_productExceptSelf : ∀ i ∈ List.range nums.length, productExceptSelf nums h_precond = List.map (fun i => (List.foldl (fun acc x => acc ++ [acc.getLast! * x]) [1] (List.take i nums)).getLast! * (List.foldl (fun acc x => acc ++ [acc.getLast! * x]) [1] (List.reverse (List.drop (i + 1) nums))).getLast!) (List.range nums.length) := by
    intros i hi
    simp [productExceptSelf];
    split_ifs <;> simp_all +decide [ computepref, computeSuffix ];
    intro a ha
    have h_foldl : (List.foldl (fun acc x => acc ++ [acc.getLast?.getD 0 * x]) [1] nums)[a]?.getD 0 = (List.foldl (fun acc x => acc ++ [acc.getLast?.getD 0 * x]) [1] (List.take a nums)).getLast?.getD 0 := by
      have h_foldl : ∀ (l : List ℤ) (a : ℕ), a < l.length → (List.foldl (fun acc x => acc ++ [acc.getLast?.getD 0 * x]) [1] l)[a]?.getD 0 = (List.foldl (fun acc x => acc ++ [acc.getLast?.getD 0 * x]) [1] (List.take a l)).getLast?.getD 0 := by
        intros l a ha; induction' l using List.reverseRecOn with l ih generalizing a; aesop;
        by_cases ha' : a < l.length <;> simp_all +decide [ List.take_append ];
        · simp_all +decide [ List.getElem?_append, Nat.sub_eq_zero_of_le ha'.le ];
          split_ifs <;> simp_all +decide [ List.getElem?_eq_none ];
          · grind;
          · have h_foldl_length : ∀ (l : List ℤ), (List.foldl (fun acc x => acc ++ [acc.getLast?.getD 0 * x]) [1] l).length = l.length + 1 := by
              intro l; induction' l using List.reverseRecOn with l ih <;> aesop;
            linarith [ h_foldl_length l ];
        · -- Since $a = l.length$, the element at position $a$ in the list is the last element of the foldl result.
          have h_last : a = l.length := by
            linarith;
          simp +decide [ h_last, List.getElem?_append ];
          -- By definition of foldl, the length of the list after foldl is equal to the length of the original list plus one.
          have h_foldl_length : ∀ (l : List ℤ), (List.foldl (fun (acc : List ℤ) (x : ℤ) => acc ++ [acc.getLast?.getD 0 * x]) [1] l).length = l.length + 1 := by
            intro l; induction' l using List.reverseRecOn with l ih <;> aesop;
          rw [ List.getLast?_eq_getElem? ] ; aesop;
      exact h_foldl nums a ha
    have h_foldr : (List.foldr (fun x y => y ++ [y.getLast?.getD 0 * x]) [1] nums).reverse[a + 1]?.getD 0 = (List.foldr (fun x y => y ++ [y.getLast?.getD 0 * x]) [1] (List.drop (a + 1) nums)).getLast?.getD 0 := by
      have h_foldr : ∀ (l : List ℤ) (n : ℕ), n ≤ l.length → (List.foldr (fun x y => y ++ [y.getLast?.getD 0 * x]) [1] l).reverse[n]?.getD 0 = (List.foldr (fun x y => y ++ [y.getLast?.getD 0 * x]) [1] (List.drop n l)).getLast?.getD 0 := by
        -- We'll use induction on the list to prove this.
        intro l n hn
        induction' l with x l ih generalizing n;
        · cases n <;> trivial;
        · rcases n with ( _ | n ) <;> simp_all +decide [ List.drop ];
      exact h_foldr _ _ ( by linarith )
    rw [h_foldl, h_foldr];
  refine' ⟨ _, _ ⟩;
  · unfold productExceptSelf; aesop;
  · grind
