/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: fd767c86-9330-453a-a8f7-d44859287694

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
This module implements a solution to the Two Sum problem in Lean 4.
It defines `twoSum` which takes a list of integers and a target integer, along with a proof that a unique solution exists.
It returns a pair of indices such that the sum of the numbers at those indices equals the target.
The correctness of the implementation is proven in `twoSum_spec_satisfied`.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

@[reducible]
def twoSum_precond (nums : List Int) (target : Int) : Prop :=
  let pairwiseSum := List.range nums.length |>.flatMap (fun i =>
    nums.drop (i + 1) |>.map (fun y => nums[i]! + y))
  nums.length > 1 ∧ pairwiseSum.count target = 1

def findComplement (nums : List Int) (target : Int) (i : Nat) (x : Int) : Option Nat :=
  let rec aux (nums : List Int) (j : Nat) : Option Nat :=
    match nums with
    | []      => none
    | y :: ys => if x + y = target then some (i + j + 1) else aux ys (j + 1)
  aux nums 0

def twoSumAux (nums : List Int) (target : Int) (i : Nat) : Prod Nat Nat :=
  match nums with
  | []      => panic! "No solution exists"
  | x :: xs =>
    match findComplement xs target i x with
    | some j => (i, j)
    | none   => twoSumAux xs target (i + 1)

def twoSum (nums : List Int) (target : Int) (h_precond : twoSum_precond (nums) (target)) : Prod Nat Nat :=
  twoSumAux nums target 0

@[reducible]
def twoSum_postcond (nums : List Int) (target : Int) (result: Prod Nat Nat) (h_precond : twoSum_precond (nums) (target)) : Prop :=
  let i := result.fst;
  let j := result.snd;
  (i < j) ∧
  (i < nums.length) ∧ (j < nums.length) ∧
  (nums[i]!) + (nums[j]!) = target

lemma findComplement_some {xs : List Int} {target : Int} {i : Nat} {x : Int} {j : Nat} :
  findComplement xs target i x = some j → i < j ∧ j <= i + xs.length ∧ ∃ k, k < xs.length ∧ j = i + 1 + k ∧ x + xs[k]! = target := by
  -- By definition of `findComplement`, if it returns `some j`, then `j` is the index of the complement of `x` in `xs`.
  intro h_findComplement
  obtain ⟨k, hk⟩ : ∃ k < xs.length, j = i + 1 + k ∧ x + xs[k]! = target := by
    -- By definition of `findComplement`, if it returns `some j`, then there exists some `k` in `xs` where `x + k = target` and `j` is the index of that `k` in `xs`. This follows directly from the definition of `findComplement`.
    have h_findComplement_spec : ∀ {xs : List ℤ} {target : ℤ} {i : ℕ} {x : ℤ} {j : ℕ}, findComplement xs target i x = some j → List.length xs ≥ 1 ∧ ∃ k < List.length xs, j = i + 1 + k ∧ x + xs[k]! = target := by
      intros xs target i x j h_findComplement; induction' xs with xs_hd xs_tl ih generalizing i x j <;> simp_all +decide [ findComplement ] ;
      · cases h_findComplement;
      · by_cases h : x + xs_hd = target <;> simp_all +decide [ findComplement.aux ];
        obtain ⟨ k, hk₁, hk₂, hk₃ ⟩ := ih ( show findComplement.aux target ( i + 1 ) x xs_tl 0 = Option.some j from by
                                              convert h_findComplement using 1;
                                              -- By definition of `findComplement.aux`, we can prove this by induction on the list `xs_tl`.
                                              have h_aux_eq : ∀ {xs : List ℤ} {target : ℤ} {i : ℕ} {x : ℤ} {j : ℕ}, findComplement.aux target (i + 1) x xs j = findComplement.aux target i x xs (j + 1) := by
                                                intros xs target i x j; induction' xs with xs_hd xs_tl ih generalizing i x j <;> simp_all +decide [ findComplement.aux ] ;
                                                ring;
                                              exact h_aux_eq );
        exact ⟨ hk₁ + 1, by linarith, by linarith, by simpa [ List.getElem?_cons ] using hk₃.2 ⟩;
    exact h_findComplement_spec h_findComplement |>.2;
  exact ⟨ by linarith, by linarith, k, hk.1, hk.2.1, hk.2.2 ⟩

lemma findComplement_none {xs : List Int} {target : Int} {i : Nat} {x : Int} :
  findComplement xs target i x = none → ∀ k, k < xs.length → x + xs[k]! ≠ target := by
  intro h k hk_lt hk_eq
  have h_aux_none : ∀ (xs : List Int) (j : Nat), findComplement.aux target i x xs j = none → ∀ k, k < xs.length → x + xs[k]! ≠ target := by
    -- By induction on the list xs, we can show that if findComplement.aux returns none, then there's no index k in xs where x + xs[k]! equals the target.
    intros xs j hj_none k hk_lt hk_eq
    induction' xs with y ys ih generalizing j k;
    · contradiction;
    · rcases k with ( _ | k ) <;> simp_all +decide [ findComplement.aux ];
      grind;
  -- Apply the lemma h_aux_none to the hypothesis h.
  apply h_aux_none xs 0 h k hk_lt hk_eq

lemma findComplement_eq_none {xs : List Int} {target : Int} {i : Nat} {x : Int} :
  (∀ k, k < xs.length → x + xs[k]! ≠ target) → findComplement xs target i x = none := by
  -- By definition of `findComplement`, if no element in `xs` satisfies `x + y = target`, then `findComplement xs target i x` returns `none`.
  intros h_no_complement
  induction' xs with y ys ih generalizing i x <;> simp_all +decide [ findComplement ];
  · -- In the base case, when the list is empty, the function returns none.
    simp [findComplement.aux];
  · -- By definition of `findComplement.aux`, if no element in `y :: ys` satisfies `x + y = target`, then `findComplement.aux target i x (y :: ys) 0` returns `none`.
    have h_aux_none : ∀ {j : ℕ} {xs : List ℤ}, (∀ k < xs.length, x + xs[k]! ≠ target) → findComplement.aux target i x xs j = none := by
      intros j xs h_no_complement; induction' xs with y ys ih generalizing j <;> simp_all +decide [ findComplement.aux ] ;
      -- Apply the induction hypothesis to the list `ys` and the parameter `j + 1`.
      have h_ind : findComplement.aux target i x ys (j + 1) = none := by
        exact ih fun k hk => h_no_complement ( k + 1 ) ( by linarith );
      exact if_neg ( h_no_complement 0 ( Nat.zero_lt_succ _ ) ) |> fun h => h.trans h_ind;
    grind

lemma twoSumAux_prop (nums : List Int) (target : Int) (i : Nat) :
  let (u, v) := twoSumAux nums target i
  u < v → i ≤ u ∧ v < i + nums.length ∧ nums[u - i]! + nums[v - i]! = target := by
  induction' nums with x xs ih generalizing i <;> simp_all +decide [ List.range_succ_eq_map ];
  · exact fun h => False.elim <| h.not_le <| by rfl;
  · by_cases h : findComplement xs target i x = none <;> simp_all +decide [ twoSumAux ];
    · grind +ring;
    · -- Since `findComplement` returns a `j`, we know that `x + xs[j - i]! = target`.
      obtain ⟨j, hj⟩ : ∃ j, findComplement xs target i x = some j := by
        exact Option.ne_none_iff_exists'.mp h;
      have := findComplement_some hj; simp_all +decide [ add_comm, add_left_comm, add_assoc ] ;
      grind

lemma twoSumAux_finds_solution (nums : List Int) (target : Int) (i : Nat) :
  (∃ u v, i ≤ u ∧ u < v ∧ v < i + nums.length ∧ nums[u-i]! + nums[v-i]! = target) →
  let (u, v) := twoSumAux nums target i
  u < v ∧ v < i + nums.length ∧ nums[u-i]! + nums[v-i]! = target := by
  intro h
  obtain ⟨u, v, hu, hv, hv_lt⟩ := h;
  induction' nums with x xs ih generalizing i <;> simp_all +decide;
  · linarith;
  · by_cases h : findComplement xs target i x = none;
    · rcases u' : u - i with ( _ | u' ) <;> rcases v' : v - i with ( _ | v' ) <;> simp_all +decide [ Nat.add_comm 1 ];
      · omega;
      · contrapose! h;
        intro H; have := findComplement_none H; simp_all +decide [ Nat.sub_eq_iff_eq_add ] ;
        grind;
      · omega;
      · rw [ Nat.sub_eq_iff_eq_add ] at u' v' <;> try linarith;
        specialize ih ( i + 1 ) ; simp_all +decide [ add_assoc ];
        convert ih ( by linarith ) ( by linarith ) _ using 1;
        · rw [ show twoSumAux ( x :: xs ) target i = twoSumAux xs target ( i + 1 ) from _ ];
          exact Eq.symm ( by rw [ show twoSumAux ( x :: xs ) target i = twoSumAux xs target ( i + 1 ) from by { rw [ show twoSumAux ( x :: xs ) target i = match findComplement xs target i x with | some j => ( i, j ) | none => twoSumAux xs target ( i + 1 ) from rfl ] ; aesop } ] );
        · rw [ show twoSumAux ( x :: xs ) target i = twoSumAux xs target ( i + 1 ) from ?_ ] ; ring;
          · rw [ show ( twoSumAux xs target ( 1 + i ) ).1 - i = ( twoSumAux xs target ( 1 + i ) ).1 - ( 1 + i ) + 1 from ?_, show ( twoSumAux xs target ( 1 + i ) ).2 - i = ( twoSumAux xs target ( 1 + i ) ).2 - ( 1 + i ) + 1 from ?_ ] <;> norm_num [ Nat.sub_add_comm ];
            · rw [ tsub_add_eq_add_tsub ];
              · grind;
              · have := twoSumAux_prop xs target ( 1 + i ) ; simp_all +decide [ add_comm 1 ] ;
                linarith;
            · rw [ tsub_add_eq_add_tsub ];
              · grind;
              · have := twoSumAux_prop xs target ( 1 + i ) ; simp_all +decide [ add_comm 1 ] ;
          · exact Eq.symm ( by rw [ show twoSumAux ( x :: xs ) target i = twoSumAux xs target ( i + 1 ) from by { rw [ show twoSumAux ( x :: xs ) target i = match findComplement xs target i x with | some j => ( i, j ) | none => twoSumAux xs target ( i + 1 ) from rfl ] ; aesop } ] );
        · convert hv_lt.2 using 1 ; ring;
          simp +arith +decide [ add_assoc, add_tsub_add_eq_tsub_left ];
    · obtain ⟨ j, hj ⟩ := Option.ne_none_iff_exists'.mp h;
      -- By definition of `twoSumAux`, if `findComplement xs target i x = some j`, then `twoSumAux (x :: xs) target i = (i, j)`.
      have h_twoSumAux : twoSumAux (x :: xs) target i = (i, j) := by
        exact Eq.symm ( by rw [ show twoSumAux ( x :: xs ) target i = ( i, j ) from by { rw [ twoSumAux ] ; aesop } ] );
      -- Since $findComplement xs target i x = some j$, we have $i < j$ and $j \leq i + xs.length$.
      have h_j_bounds : i < j ∧ j ≤ i + xs.length := by
        exact findComplement_some hj |> fun ⟨ hj₁, hj₂, hj₃ ⟩ => ⟨ hj₁, hj₂ ⟩;
      -- By definition of `findComplement`, if `findComplement xs target i x = some j`, then `x + (xs.get! (j - (i + 1))) = target`.
      have h_findComplement : x + (xs.get! (j - (i + 1))) = target := by
        have := findComplement_some hj; aesop;
      simp_all +decide [ Nat.sub_sub ];
      exact ⟨ by linarith, by rw [ show j - i = j - ( i + 1 ) + 1 by omega ] ; aesop ⟩

lemma mem_pairwiseSum_iff_exists_pair {nums : List Int} {x : Int} :
  x ∈ (List.range nums.length |>.flatMap (fun i => nums.drop (i + 1) |>.map (fun y => nums[i]! + y))) ↔
  ∃ i j, i < j ∧ j < nums.length ∧ nums[i]! + nums[j]! = x := by
  constructor;
  · simp +zetaDelta at *;
    intro i hi hx;
    rw [ List.mem_iff_get ] at hx;
    obtain ⟨ n, hn ⟩ := hx;
    use i, n + i + 1;
    grind;
  · -- If there exist indices i and j such that i < j, j < nums.length, and nums[i]! + nums[j]! = x, then x is in the flatMap of the pairwise sums.
    intro h
    obtain ⟨i, j, hij, hj, hx⟩ := h
    have h_exists : x ∈ List.map (fun y => nums[i]! + y) (List.drop (i + 1) nums) := by
      rw [ List.mem_iff_get ];
      use ⟨ j - ( i + 1 ), by
        simp +arith +decide [ hj.le ];
        omega ⟩
      generalize_proofs at *;
      grind;
    exact List.mem_flatMap.mpr ⟨ i, List.mem_range.mpr ( by linarith ), h_exists ⟩

lemma precond_implies_exists_pair {nums : List Int} {target : Int} :
  twoSum_precond nums target → ∃ i j, i < j ∧ j < nums.length ∧ nums[i]! + nums[j]! = target := by
  -- By definition of `twoSum_precond`, if the condition holds, then there exists a unique pair (i, j) such that i < j and nums[i]! + nums[j]! = target. This follows from the fact that the count of the target in the pairwise sums is 1.
  intros h_precond
  have h_pair : ∃ i j, i < j ∧ j < nums.length ∧ nums[i]! + nums[j]! = target := by
    have h_count : (List.range nums.length |>.flatMap (fun i => nums.drop (i + 1) |>.map (fun y => nums[i]! + y))).count target = 1 := by
      grind
    have h_pair : target ∈ (List.range nums.length |>.flatMap (fun i => nums.drop (i + 1) |>.map (fun y => nums[i]! + y))) := by
      -- Since the count of the target in the list is 1, the target must be present in the list.
      have h_target_in_list : target ∈ List.flatMap (fun i => List.map (fun y => nums[i]! + y) (List.drop (i + 1) nums)) (List.range nums.length) := by
        have h_count_pos : 0 < List.count target (List.flatMap (fun i => List.map (fun y => nums[i]! + y) (List.drop (i + 1) nums)) (List.range nums.length)) := by linarith
        contrapose! h_count_pos; simp_all +decide [ List.count_eq_zero_of_not_mem ] ;
      assumption;
    exact?;
  -- Apply the hypothesis `h_pair` to conclude the proof.
  apply h_pair

theorem twoSum_spec_satisfied (nums: List Int) (target: Int) (h_precond : twoSum_precond (nums) (target)) :
    twoSum_postcond (nums) (target) (twoSum (nums) (target) h_precond) h_precond := by
  -- By `precond_implies_exists_pair`, there exists a pair (i, j) such that i < j and nums[i]! + nums[j]! = target.
  obtain ⟨i, j, hij, h_pair⟩ : ∃ i j, i < j ∧ j < nums.length ∧ nums[i]! + nums[j]! = target := by
    exact?;
  have := twoSumAux_finds_solution nums target 0 ⟨ i, j, by linarith, by linarith, by linarith, by aesop ⟩ ; simp_all +decide [ twoSum ];
  grind
