/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 4d4dc9b3-718b-4ebe-8a70-239a1931c196

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
We define the `twoSum` function and its specification.
We introduce a helper function `twoSum_aux` that mirrors the internal loop of `twoSum` but is easier to reason about.
We prove that `twoSum` is equivalent to `twoSum_aux` with appropriate initial arguments.
We prove the soundness of `twoSum_aux`: if it returns a result, that result is a valid solution.
We prove the completeness of `twoSum_aux`: if a unique solution exists, `twoSum_aux` will find it given sufficient fuel.
Finally, we prove `twoSum_spec_satisfied`, showing that `twoSum` satisfies the postcondition given the precondition.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

@[reducible] def twoSum_precond (nums : Array Int) (target : Int) : Prop :=
  -- The array must have at least 2 elements
  nums.size ≥ 2 ∧
  -- There exists exactly one pair of indices whose values sum to the target
  (List.range nums.size).any (fun i =>
    (List.range i).any (fun j => nums[i]! + nums[j]! = target)) ∧
  -- No other pair sums to the target (ensuring uniqueness of solution)
  ((List.range nums.size).flatMap (fun i =>
    (List.range i).filter (fun j => nums[i]! + nums[j]! = target))).length = 1

def twoSum (nums : Array Int) (target : Int) (h_precond : twoSum_precond (nums) (target)) : Array Nat :=
  let rec findIndices (i : Nat) (j : Nat) (fuel : Nat) : Array Nat :=
    match fuel with
    | 0 => #[] -- Fuel exhausted, return empty array
    | fuel+1 =>
      if i >= nums.size then
        #[] -- No solution found
      else if j >= nums.size then
        findIndices (i + 1) (i + 2) fuel -- Move to next i and reset j
      else
        if nums[i]! + nums[j]! == target then
          #[i, j] -- Found solution
        else
          findIndices i (j + 1) fuel -- Try next j
   findIndices 0 1 (nums.size * nums.size)

@[reducible] def twoSum_postcond (nums : Array Int) (target : Int) (result: Array Nat) (h_precond : twoSum_precond (nums) (target)) : Prop :=
  -- Result contains exactly 2 indices
  result.size = 2 ∧
  -- The indices are valid (within bounds of the nums array)
  result[0]! < nums.size ∧ result[1]! < nums.size ∧
  -- The indices are in ascending order (sorted)
  result[0]! < result[1]! ∧
  -- The values at these indices sum to the target
  nums[result[0]!]! + nums[result[1]!]! = target

/-
A helper function mirroring the logic of `twoSum`'s internal loop.
-/
def twoSum_aux (nums : Array Int) (target : Int) (i j fuel : Nat) : Array Nat :=
  match fuel with
  | 0 => #[]
  | fuel+1 =>
    if i >= nums.size then
      #[]
    else if j >= nums.size then
      twoSum_aux nums target (i + 1) (i + 2) fuel
    else
      if nums[i]! + nums[j]! == target then
        #[i, j]
      else
        twoSum_aux nums target i (j + 1) fuel

theorem twoSum_eq_aux (nums : Array Int) (target : Int) (h : twoSum_precond nums target) :
  twoSum nums target h = twoSum_aux nums target 0 1 (nums.size * nums.size) := by
  rw [twoSum]
  let rec findIndices_eq_aux (i j fuel : Nat) :
    twoSum.findIndices nums target i j fuel = twoSum_aux nums target i j fuel := by
    induction fuel generalizing i j
    case zero => rfl
    case succ fuel ih =>
      rw [twoSum.findIndices, twoSum_aux]
      split
      · rfl
      · split
        · rw [ih]
        · split
          · rfl
          · rw [ih]
  apply findIndices_eq_aux

/-
If `twoSum_aux` returns a result of size 2, then the result contains valid indices `u, v` such that `u < v` and `nums[u] + nums[v] = target`. This assumes the invariant `i < j` holds for the inputs.
-/
theorem twoSum_aux_soundness (nums : Array Int) (target : Int) (i j fuel : Nat)
  (h_ij : i < j) :
  let res := twoSum_aux nums target i j fuel
  res.size = 2 →
  res[0]! < nums.size ∧ res[1]! < nums.size ∧ res[0]! < res[1]! ∧ nums[res[0]!]! + nums[res[1]!]! = target := by
    induction' fuel with fuel ih generalizing i j;
    · cases i <;> cases j <;> tauto;
    · simp +zetaDelta at * ; by_cases hj : j ≥ nums.size <;> simp_all +decide [ twoSum_aux ];
      · grind;
      · grind

/-
If `twoSum_aux` is searching in the row `u` where the solution `(u, v)` is located, and `j <= v`, and no other solution exists in this row before `v`, then it returns `#[u, v]`.
-/
theorem twoSum_aux_in_row (nums : Array Int) (target : Int) (u v : Nat) (fuel : Nat)
  (hu : u < nums.size) (hv : v < nums.size) (huv : u < v)
  (h_target : nums[u]! + nums[v]! = target)
  (h_unique_row : ∀ k, u < k → k < v → nums[u]! + nums[k]! ≠ target)
  (j : Nat) (hj_le_v : j ≤ v) (hj_gt_u : u < j)
  (h_fuel : fuel > v - j) :
  twoSum_aux nums target u j fuel = #[u, v] := by
    induction' n : v - j using Nat.strong_induction_on with n ih generalizing j fuel;
    rcases fuel with ( _ | fuel ) <;> simp_all +decide [ twoSum_aux ];
    grind

/-
If row `i` contains no solution for indices `k >= j`, then `twoSum_aux` will eventually skip row `i` and proceed to row `i+1`, consuming the appropriate amount of fuel.
-/
theorem twoSum_aux_skip_row (nums : Array Int) (target : Int) (i j fuel : Nat)
  (h_no_sol : ∀ k, j ≤ k → k < nums.size → nums[i]! + nums[k]! ≠ target)
  (h_j_le_size : j ≤ nums.size)
  (h_fuel : fuel ≥ nums.size - j + 1) :
  twoSum_aux nums target i j fuel = twoSum_aux nums target (i + 1) (i + 2) (fuel - (nums.size - j + 1)) := by
    induction' h : nums.size - j with k hk generalizing i j fuel;
    · cases h_j_le_size.eq_or_lt <;> simp_all +decide [ Nat.sub_eq_iff_eq_add ];
      rcases fuel with ( _ | _ | fuel ) <;> simp_all +decide [ twoSum_aux ];
      intros; linarith;
    · convert hk i ( j + 1 ) ( fuel - 1 ) ( fun k hk₁ hk₂ => h_no_sol k ( by linarith ) hk₂ ) ( by omega ) ( by omega ) _ using 1;
      · rcases fuel with ( _ | fuel ) <;> simp_all +decide;
        rw [ twoSum_aux ];
        split_ifs <;> simp_all +decide [ Nat.sub_add_cancel ];
        exact Nat.recOn fuel ( by rfl ) fun n ihn => by rw [ twoSum_aux ] ; aesop;
      · rw [ Nat.sub_sub ];
        ring;
      · omega

/-
The precondition guarantees the existence of a unique pair of indices `(u, v)` such that `u < v` and their values sum to `target`.
-/
theorem exists_unique_pair (nums : Array Int) (target : Int) (h : twoSum_precond nums target) :
  ∃ u v, u < v ∧ v < nums.size ∧ nums[u]! + nums[v]! = target ∧
  ∀ a b, a < b → b < nums.size → nums[a]! + nums[b]! = target → a = u ∧ b = v := by
  rcases h with ⟨ h₁, h₂, h₃ ⟩;
  have h_unique : ∃ p : ℕ × ℕ, p ∈ (List.range nums.size).flatMap (fun i => (List.range i).filter (fun j => nums[i]! + nums[j]! = target) |>.map (fun j => (i, j))) ∧ ∀ q : ℕ × ℕ, q ∈ (List.range nums.size).flatMap (fun i => (List.range i).filter (fun j => nums[i]! + nums[j]! = target) |>.map (fun j => (i, j))) → q = p := by
    have h_unique : List.length (List.flatMap (fun i => (List.range i).filter (fun j => nums[i]! + nums[j]! = target) |>.map (fun j => (i, j))) (List.range nums.size)) = 1 := by
      convert h₃ using 1;
      induction ( List.range nums.size ) <;> aesop;
    rw [ List.length_eq_one_iff ] at h_unique; obtain ⟨ p, hp ⟩ := h_unique; use p; aesop;
  obtain ⟨ ⟨ u, v ⟩, hp₁, hp₂ ⟩ := h_unique;
  simp +zetaDelta at *;
  exact ⟨ v, u, hp₁.2.1, hp₁.1, by linarith, fun a b hab hba h => by specialize hp₂ _ _ b hba a hab ( by linarith ) rfl rfl; aesop ⟩

/-
If `(u, v)` is the unique solution with `u < v`, and we start searching at row `i \le u` with sufficient fuel, `twoSum_aux` will return `#[u, v]`.
-/
theorem twoSum_aux_finds_unique (nums : Array Int) (target : Int) (u v : Nat)
  (hu : u < nums.size) (hv : v < nums.size) (huv : u < v)
  (h_target : nums[u]! + nums[v]! = target)
  (h_unique : ∀ a b, a < b → b < nums.size → nums[a]! + nums[b]! = target → a = u ∧ b = v)
  (i : Nat) (hi : i ≤ u)
  (fuel : Nat) (h_fuel : fuel ≥ (u - i + 1) * nums.size) :
  twoSum_aux nums target i (i + 1) fuel = #[u, v] := by
    induction' h : u - i with d hd generalizing i fuel;
    · -- Apply the `twoSum_aux_in_row` theorem to show that the result is `#[u, v]`.
      have h_aux : twoSum_aux nums target i (i + 1) fuel = #[i, v] := by
        have h_no_sol : ∀ k, i < k → k < v → nums[i]! + nums[k]! ≠ target := by
          grind
        apply twoSum_aux_in_row;
        any_goals omega;
        · grind;
        · nlinarith [ Nat.sub_add_cancel ( by linarith : i + 1 ≤ v ) ];
      grind;
    · -- By definition of `twoSum_aux`, we know that if `i < u`, then `twoSum_aux nums target i (i + 1) fuel` will skip row `i` and proceed to row `i + 1`.
      have h_skip : twoSum_aux nums target i (i + 1) fuel = twoSum_aux nums target (i + 1) (i + 2) (fuel - (nums.size - (i + 1) + 1)) := by
        apply twoSum_aux_skip_row;
        · intro k hk₁ hk₂ hk₃; specialize h_unique i k ( by linarith ) ( by linarith ) hk₃; omega;
        · linarith [ Nat.sub_add_cancel hi ];
        · nlinarith [ Nat.sub_add_cancel ( by linarith : i + 1 ≤ nums.size ) ];
      rw [ h_skip, hd ];
      · omega;
      · rw [ show u - ( i + 1 ) = u - i - 1 by rw [ Nat.sub_sub ] ];
        exact le_tsub_of_add_le_left ( by nlinarith only [ h_fuel, Nat.sub_add_cancel ( by linarith : 1 ≤ u - i ), Nat.sub_add_cancel ( by linarith : i + 1 ≤ nums.size ) ] );
      · omega

/-
The `twoSum` function satisfies its postcondition, meaning it returns the correct unique pair of indices.
-/
theorem twoSum_spec_satisfied (nums: Array Int) (target: Int) (h_precond : twoSum_precond (nums) (target)) :
  twoSum_postcond (nums) (target) (twoSum (nums) (target) h_precond) h_precond := by
  -- By definition of `twoSum_aux`, there exist unique indices `u` and `v` such that `u < v`, `v < nums.size`, and `nums[u]! + nums[v]! = target`.
  obtain ⟨u, v, huv₁, huv₂, huv₃⟩ : ∃ u v, u < v ∧ v < nums.size ∧ nums[u]! + nums[v]! = target ∧
    (∀ a b, a < b → b < nums.size → nums[a]! + nums[b]! = target → a = u ∧ b = v) := by
      exact?;
  -- By definition of `twoSum_aux`, there exist unique indices `u` and `v` such that `u < v`, `v < nums.size`, and `nums[u]! + nums[v]! = target`. We can use these indices to show that `twoSum_aux` returns `#[u, v]`.
  have h_twoSum_aux : twoSum_aux nums target 0 1 (nums.size * nums.size) = #[u, v] := by
    apply twoSum_aux_finds_unique;
    any_goals nlinarith;
    · exact huv₃.2;
    · simp +zetaDelta at *;
      nlinarith;
  rw [ twoSum_eq_aux ];
  grind
