/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 619aa47a-be49-4c5d-8113-dec22208061b

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
This module defines and verifies an algorithm to compute the nth ugly number.
It includes:
- `IsUgly`: A predicate defining ugly numbers (positive integers with prime factors only 2, 3, 5).
- `nthUglyNumber`: The main function that computes the nth ugly number using a dynamic programming approach.
- `LoopInvariant`: A loop invariant that ensures the correctness of the algorithm's state at each step.
- `nthUglyNumber_spec_satisfied`: The main theorem proving that `nthUglyNumber` returns the correct nth ugly number.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

@[reducible, simp]
def nthUglyNumber_precond (n : Nat) : Prop :=
  n > 0

def nextUgly (seq : List Nat) (c2 c3 c5 : Nat) : (Nat × Nat × Nat × Nat) :=
  let i2 := seq[c2]! * 2
  let i3 := seq[c3]! * 3
  let i5 := seq[c5]! * 5
  let next := min i2 (min i3 i5)
  let c2' := if next = i2 then c2 + 1 else c2
  let c3' := if next = i3 then c3 + 1 else c3
  let c5' := if next = i5 then c5 + 1 else c5
  (next, c2', c3', c5')

def nthUglyNumber (n : Nat) (h_precond : nthUglyNumber_precond (n)) : Nat :=
  let rec loop (i : Nat) (seq : List Nat) (c2 c3 c5 : Nat) : List Nat :=
    match i with
    | 0 => seq
    | Nat.succ i' =>
      let (next, c2', c3', c5') := nextUgly seq c2 c3 c5
      loop i' (seq ++ [next]) c2' c3' c5'
  (loop (n - 1) [1] 0 0 0)[(n - 1)]!

def divideOut : Nat → Nat → Nat
  | n, p =>
    if h : p > 1 ∧ n > 0 ∧ n % p = 0 then
      have : n / p < n := by
        apply Nat.div_lt_self
        · exact h.2.1  -- n > 0
        · exact Nat.lt_of_succ_le (Nat.succ_le_of_lt h.1)  -- 1 < p, so 2 ≤ p
      divideOut (n / p) p
    else n
termination_by n p => n

def isUgly (x : Nat) : Bool :=
  if x = 0 then
    false
  else
    let n1 := divideOut x 2
    let n2 := divideOut n1 3
    let n3 := divideOut n2 5
    n3 = 1

@[reducible, simp]
def nthUglyNumber_postcond (n : Nat) (result: Nat) (h_precond : nthUglyNumber_precond (n)) : Prop :=
  isUgly result = true ∧
  ((List.range (result)).filter (fun i => isUgly i)).length = n - 1

def IsUgly (n : Nat) : Prop := n > 0 ∧ ∀ p, Nat.Prime p → p ∣ n → p = 2 ∨ p = 3 ∨ p = 5

theorem divideOut_spec (n p : Nat) (hp : p > 1) (hn : n > 0) :
    let n' := divideOut n p
    n' ∣ n ∧ ¬ (p ∣ n') ∧ ∀ q, Nat.Prime q → q ∣ n' → q ∣ n := by
  induction' n using Nat.strong_induction_on with n ih generalizing p;
  by_cases h : p > 1 ∧ n > 0 ∧ n % p = 0;
  · -- If $p$ divides $n$, then $n = p * m$ for some $m$, and we can apply the induction hypothesis to $m$.
    obtain ⟨m, hm⟩ : ∃ m, n = p * m := by
      exact Nat.dvd_of_mod_eq_zero h.2.2;
    -- By definition of `divideOut`, we have `divideOut (p * m) p = divideOut m p`.
    have h_div : divideOut (p * m) p = divideOut m p := by
      rw [ divideOut ];
      simp +decide [ hm, Nat.mul_div_cancel_left _ hp.le ];
      exact fun h => absurd ( h hp ( pos_of_gt hp ) ) ( by aesop );
    by_cases hm_pos : m > 0 <;> simp_all +decide [ Nat.dvd_iff_mod_eq_zero ];
    exact ⟨ Nat.mod_eq_zero_of_dvd <| dvd_mul_of_dvd_right ( Nat.dvd_of_mod_eq_zero <| ih m ( by nlinarith ) p h hm_pos |>.1 ) _, fun q hq hq' => Nat.mod_eq_zero_of_dvd <| dvd_mul_of_dvd_right ( Nat.dvd_of_mod_eq_zero <| ih m ( by nlinarith ) p h hm_pos |>.2.2 q hq hq' ) _ ⟩;
  · -- Since $p$ does not divide $n$, we have $divideOut n p = n$.
    have h_div : divideOut n p = n := by
      -- Since $p$ does not divide $n$, we have $divideOut n p = n$ by definition.
      simp [divideOut, h];
    simp_all +decide [ Nat.dvd_iff_mod_eq_zero ]

theorem isUgly_iff_IsUgly (n : Nat) : isUgly n = true ↔ IsUgly n := by
  -- By definition of `isUgly`, we know that `isUgly n` is true if and only if `n` is positive and all its prime factors are 2, 3, or 5.
  simp [isUgly, IsUgly];
  constructor <;> intro h;
  · -- By definition of `divideOut`, if `divideOut (divideOut (divideOut n 2) 3) 5 = 1`, then `n` is divisible only by 2, 3, and 5.
    have h_div : ∀ p, Nat.Prime p → p ∣ n → p = 2 ∨ p = 3 ∨ p = 5 := by
      -- If `divideOut (divideOut (divideOut n 2) 3) 5 = 1`, then `n` must be of the form $2^a * 3^b * 5^c$ for some non-negative integers $a$, $b$, and $c$.
      have h_form : ∃ a b c : ℕ, n = 2^a * 3^b * 5^c := by
        -- By definition of `divideOut`, if `divideOut (divideOut (divideOut n 2) 3) 5 = 1`, then `n` must be of the form $2^a * 3^b * 5^c$ for some non-negative integers $a$, $b$, and $c$. We can prove this by induction on the number of divisions. First, we apply `h_div_induction` to `divideOut (divideOut n 2) 3`.
        obtain ⟨a, ha⟩ : ∃ a : ℕ, divideOut (divideOut n 2) 3 = 5^a := by
          have h_div_induction : ∀ m : ℕ, divideOut m 5 = 1 → ∃ a : ℕ, m = 5^a := by
            intros m hm
            induction' m using Nat.strong_induction_on with m ih;
            unfold divideOut at hm;
            split_ifs at hm <;> simp_all +decide;
            · obtain ⟨ a, ha ⟩ := ih ( m / 5 ) ( Nat.div_lt_self ( by linarith ) ( by linarith ) ) hm; exact ⟨ a + 1, by rw [ pow_succ', ← ha, Nat.mul_div_cancel' ( Nat.dvd_of_mod_eq_zero ( by linarith ) ) ] ⟩ ;
            · exists 0;
          exact h_div_induction _ h.2;
        -- By definition of `divideOut`, if `divideOut (divideOut n 2) 3 = 5^a`, then `divideOut n 2` must be of the form $3^b * 5^a$ for some non-negative integer $b$.
        have h_div_induction2 : ∀ m : ℕ, divideOut m 3 = 5^a → ∃ b : ℕ, m = 3^b * 5^a := by
          intros m hm
          induction' m using Nat.strong_induction_on with m ih;
          unfold divideOut at hm;
          split_ifs at hm <;> simp_all +decide [ Nat.pow_succ', Nat.mul_assoc ];
          obtain ⟨ b, hb ⟩ := ih ( m / 3 ) ( Nat.div_lt_self ( by linarith ) ( by linarith ) ) hm; exact ⟨ b + 1, by rw [ pow_succ', mul_assoc, ← hb, Nat.mul_div_cancel' ( Nat.dvd_of_mod_eq_zero ( by tauto ) ) ] ⟩ ;
        obtain ⟨ b, hb ⟩ := h_div_induction2 _ ha;
        -- By definition of `divideOut`, if `divideOut n 2 = 3^b * 5^a`, then `n` must be of the form $2^c * 3^b * 5^a$ for some non-negative integer $c$.
        have h_div_induction3 : ∀ m : ℕ, divideOut m 2 = 3^b * 5^a → ∃ c : ℕ, m = 2^c * 3^b * 5^a := by
          intros m hm
          induction' m using Nat.strong_induction_on with m ih;
          unfold divideOut at hm;
          split_ifs at hm <;> simp_all +decide [ Nat.div_mul_cancel ( Nat.dvd_of_mod_eq_zero _ ) ];
          obtain ⟨ c, hc ⟩ := ih ( m / 2 ) ( Nat.div_lt_self ( by linarith ) ( by linarith ) ) hm; exact ⟨ c + 1, by rw [ pow_succ', mul_assoc ] ; linarith [ Nat.mod_add_div m 2 ] ⟩ ;
        exact Exists.elim ( h_div_induction3 n hb ) fun c hc => ⟨ c, b, a, hc ⟩;
      rcases h_form with ⟨ a, b, c, rfl ⟩ ; intro p pp dp; simp_all +decide [ Nat.Prime.dvd_mul ] ;
      rcases dp with ( ( dp | dp ) | dp ) <;> have := pp.dvd_of_dvd_pow dp <;> have := Nat.le_of_dvd ( by decide ) this <;> interval_cases p <;> trivial;
    exact ⟨ Nat.pos_of_ne_zero h.1, h_div ⟩;
  · -- By definition of divideOut, we know that if n is divisible by 2, 3, or 5, then divideOut will remove those factors.
    have h_div : ∀ {n : ℕ}, 0 < n → (∀ p, Nat.Prime p → p ∣ n → p = 2 ∨ p = 3 ∨ p = 5) → divideOut n 2 = n / 2 ^ (Nat.factorization n 2) := by
      intros n hn h; induction' n using Nat.strongRecOn with n ih; rcases n with ( _ | _ | n ) <;> simp_all +decide [ Nat.factorization_eq_zero_of_not_dvd ] ;
      · native_decide +revert;
      · by_cases h₂ : 2 ∣ n + 2;
        · obtain ⟨ k, hk ⟩ := h₂; simp_all +decide [ Nat.factorization_eq_zero_of_not_dvd ] ;
          unfold divideOut; simp +decide [ Nat.factorization_mul, show k ≠ 0 by linarith ] ;
          rw [ ih k ( by linarith ) ( by linarith ) ( fun p pp dp => h p pp ( dvd_mul_of_dvd_right dp _ ) ) ] ; split_ifs <;> simp_all +decide [ Nat.pow_add, Nat.mul_div_mul_left ];
        · unfold divideOut; simp_all +decide [ Nat.factorization_eq_zero_of_not_dvd ] ;
          omega;
    -- Applying divideOut three times will remove all factors of 2, 3, and 5, leaving 1.
    have h_div3 : divideOut (divideOut (n / 2 ^ (Nat.factorization n 2)) 3) 5 = (n / 2 ^ (Nat.factorization n 2)) / 3 ^ (Nat.factorization (n / 2 ^ (Nat.factorization n 2)) 3) / 5 ^ (Nat.factorization ((n / 2 ^ (Nat.factorization n 2)) / 3 ^ (Nat.factorization (n / 2 ^ (Nat.factorization n 2)) 3)) 5) := by
      have h_div3 : ∀ {n : ℕ}, 0 < n → (∀ p, Nat.Prime p → p ∣ n → p = 2 ∨ p = 3 ∨ p = 5) → divideOut n 3 = n / 3 ^ (Nat.factorization n 3) := by
        intros n hn h; induction' n using Nat.strong_induction_on with n ih; rcases eq_or_ne n 0 with rfl | hn' <;> simp_all +decide [ Nat.factorization_eq_zero_of_not_dvd ] ;
        unfold divideOut; simp +decide [ hn', h ] ;
        -- If $n$ is divisible by 3, then $n = 3 * k$ for some $k$, and we can apply the induction hypothesis to $k$.
        by_cases h3 : n % 3 = 0;
        · rw [ if_pos ⟨ hn, h3 ⟩, ih ( n / 3 ) ( Nat.div_lt_self hn ( by decide ) ) ( Nat.div_pos ( Nat.le_of_dvd hn ( Nat.dvd_of_mod_eq_zero h3 ) ) ( by decide ) ) ];
          · rw [ Nat.factorization_div ( Nat.dvd_of_mod_eq_zero h3 ) ] ; norm_num [ Nat.pow_succ', ← Nat.div_div_eq_div_mul ];
            rw [ Nat.div_div_eq_div_mul, ← pow_succ', Nat.sub_add_cancel ( Nat.pos_of_ne_zero ( Finsupp.mem_support_iff.mp ( by { exact Nat.mem_primeFactors.mpr ⟨ by norm_num, Nat.dvd_of_mod_eq_zero h3, hn' ⟩ } ) ) ) ];
          · exact fun p pp dp => h p pp ( dvd_trans dp ( Nat.div_dvd_of_dvd ( Nat.dvd_of_mod_eq_zero h3 ) ) );
        · simp_all +decide [ Nat.factorization_eq_zero_of_not_dvd, Nat.dvd_iff_mod_eq_zero ];
      have h_div5 : ∀ {n : ℕ}, 0 < n → (∀ p, Nat.Prime p → p ∣ n → p = 2 ∨ p = 3 ∨ p = 5) → divideOut n 5 = n / 5 ^ (Nat.factorization n 5) := by
        intros n hn h; induction' n using Nat.strongRecOn with n ih;
        by_cases h5 : 5 ∣ n;
        · obtain ⟨ k, rfl ⟩ := h5;
          rw [ Nat.factorization_mul ] <;> norm_num;
          · unfold divideOut; norm_num [ Nat.pow_add, Nat.mul_div_mul_left ] ;
            rw [ if_pos ( by linarith ), ih k ( by linarith ) ( by linarith ) fun p pp dp => h p pp ( dvd_mul_of_dvd_right dp _ ) ];
          · linarith;
        · unfold divideOut; simp +decide [ h5 ] ;
          rw [ Nat.factorization_eq_zero_of_not_dvd h5 ] ; simp +decide [ hn ];
          exact fun h => False.elim <| h5 <| Nat.dvd_of_mod_eq_zero h;
      -- Applying h_div3 and h_div5 to the intermediate steps.
      have h_div3_step : divideOut (n / 2 ^ (Nat.factorization n 2)) 3 = (n / 2 ^ (Nat.factorization n 2)) / 3 ^ (Nat.factorization (n / 2 ^ (Nat.factorization n 2)) 3) := by
        apply h_div3;
        · exact Nat.div_pos ( Nat.le_of_dvd h.1 ( Nat.ordProj_dvd _ _ ) ) ( pow_pos ( by decide ) _ );
        · exact fun p pp dp => h.2 p pp ( dvd_trans dp ( Nat.div_dvd_of_dvd ( Nat.ordProj_dvd _ _ ) ) )
      have h_div5_step : divideOut ((n / 2 ^ (Nat.factorization n 2)) / 3 ^ (Nat.factorization (n / 2 ^ (Nat.factorization n 2)) 3)) 5 = ((n / 2 ^ (Nat.factorization n 2)) / 3 ^ (Nat.factorization (n / 2 ^ (Nat.factorization n 2)) 3)) / 5 ^ (Nat.factorization ((n / 2 ^ (Nat.factorization n 2)) / 3 ^ (Nat.factorization (n / 2 ^ (Nat.factorization n 2)) 3)) 5) := by
        apply h_div5;
        · exact Nat.div_pos ( Nat.le_of_dvd ( Nat.div_pos ( Nat.le_of_dvd h.1 ( Nat.ordProj_dvd _ _ ) ) ( pow_pos ( by decide ) _ ) ) ( Nat.ordProj_dvd _ _ ) ) ( pow_pos ( by decide ) _ );
        · intro p pp dp; have := h.2 p pp ( dvd_trans dp ( Nat.dvd_trans ( Nat.div_dvd_of_dvd <| Nat.ordProj_dvd _ _ ) <| Nat.div_dvd_of_dvd <| Nat.ordProj_dvd _ _ ) ) ; tauto;
      rw [ h_div3_step, h_div5_step ];
    -- Since $n$ is positive and all its prime factors are 2, 3, or 5, we can write $n$ as $2^a \cdot 3^b \cdot 5^c$ for some non-negative integers $a$, $b$, and $c$.
    obtain ⟨a, b, c, hn⟩ : ∃ a b c : ℕ, n = 2^a * 3^b * 5^c := by
      rw [ ← Nat.factorization_prod_pow_eq_self h.1.ne' ];
      rw [ Finsupp.prod_of_support_subset ];
      case s => exact { 2, 3, 5 };
      · exact ⟨ n.factorization 2, n.factorization 3, n.factorization 5, by simp +decide [ mul_assoc ] ⟩;
      · intro p hp; specialize h; aesop;
      · exact?;
    simp_all +decide [ Nat.factorization_mul, Nat.factorization_pow ];
    norm_num [ Nat.mul_assoc, Nat.mul_div_assoc ]

theorem IsUgly_mul_2 {n : Nat} (h : IsUgly n) : IsUgly (n * 2) := by
  -- Since $n$ is ugly, multiplying it by $2$ will also result in an ugly number because $2$ is a prime factor of the resulting number.
  obtain ⟨hn_pos, hn_factors⟩ := h;
  use by
    -- Since $n$ is positive and $2$ is positive, their product $n * 2$ is also positive.
    apply mul_pos hn_pos (by norm_num);
  intro p hp_prime hp_div;
  have h_div_n : p ∣ n ∨ p = 2 := by
    -- Since $p$ is prime and divides $n * 2$, it must divide either $n$ or $2$.
    have h_div_n_or_2 : p ∣ n ∨ p ∣ 2 := by
      exact hp_prime.dvd_mul.mp hp_div
    generalize_proofs at *;
    exact Or.imp id ( fun h => by have := Nat.le_of_dvd ( by decide ) h; interval_cases p <;> trivial ) h_div_n_or_2
  generalize_proofs at *;
  grind

theorem IsUgly_mul_3 {n : Nat} (h : IsUgly n) : IsUgly (n * 3) := by
  -- Since $n$ is ugly, it is positive and all its prime factors are $2$, $3$, or $5$. Multiplying $n$ by $3$ preserves these properties.
  have h_pos : 0 < n * 3 := by
    -- Since $n$ is positive by definition of IsUgly, multiplying it by $3$ (which is positive) preserves positivity.
    apply mul_pos; exact h.left; norm_num
  have h_prime_factors : ∀ p, Nat.Prime p → p ∣ n * 3 → p = 2 ∨ p = 3 ∨ p = 5 := by
    -- Since $p$ divides $n \cdot 3$, it must divide either $n$ or $3$. If $p$ divides $3$, then $p = 3$. If $p$ divides $n$, then by the induction hypothesis, $p$ must be $2$, $3$, or $5$.
    intros p hp hdiv
    have hdiv_n_or_3 : p ∣ n ∨ p ∣ 3 := by
      exact?;
    -- If $p$ divides $n$, then by the definition of $IsUgly$, $p$ must be $2$, $3$, or $5$.
    cases' hdiv_n_or_3 with hdiv_n hdiv_3;
    · exact h.2 p hp hdiv_n;
    · have := Nat.le_of_dvd ( by decide ) hdiv_3; interval_cases p <;> trivial;
  exact ⟨h_pos, h_prime_factors⟩

theorem IsUgly_mul_5 {n : Nat} (h : IsUgly n) : IsUgly (n * 5) := by
  -- By definition of IsUgly, if n is ugly, then multiplying it by 5 (which is a prime factor of an ugly number) should still result in an ugly number.
  unfold IsUgly at *;
  -- Since n is positive, multiplying it by 5 will keep it positive. So n*5 > 0 is straightforward.
  simp [h.left];
  -- If p divides n*5, then by the properties of primes, p must divide n or p must divide 5.
  intros p hp hdiv
  have hdiv_n_or_5 : p ∣ n ∨ p ∣ 5 := by
    -- Since p is prime and divides n*5, by Euclid's lemma, p must divide n or p must divide 5.
    apply hp.dvd_mul.mp hdiv;
  -- If p divides 5, then since 5 is a prime number, the only prime divisors of 5 are 5 itself. Therefore, p must be 5.
  cases' hdiv_n_or_5 with hdiv_n hdiv_5;
  · -- Apply the hypothesis h to conclude that p must be 2, 3, or 5.
    apply h.right p hp hdiv_n;
  · -- Since 5 is a prime number, its only prime divisor is 5 itself. Therefore, if p divides 5, then p must be 5.
    have h_prime_5 : p ∣ 5 → p = 5 := by
      exact fun h => by have := Nat.le_of_dvd ( by decide ) h; interval_cases p <;> trivial;
    exact Or.inr <| Or.inr <| h_prime_5 hdiv_5

theorem IsUgly_one : IsUgly 1 := by
  -- By definition, 1 is an ugly number because it has no prime factors.
  simp [IsUgly];
  -- Since primes are greater than 1, the assumption p = 1 leads to a contradiction.
  intros p hp h_eq_one
  exfalso
  exact Nat.Prime.ne_one hp h_eq_one

def IsUglySeq (l : List Nat) : Prop :=
  l.Sorted (· < ·) ∧
  l ≠ [] ∧
  (∀ x ∈ l, IsUgly x) ∧
  (∀ y, IsUgly y → y < l.getLastD 0 → y ∈ l)

theorem IsUglySeq_singleton_one : IsUglySeq [1] := by
  -- The base case is when the list is empty. We need to show that 1 is ugly.
  simp [IsUglySeq];
  -- The number 1 is considered ugly.
  simp [IsUgly];
  -- The first part of the conjunction is trivially true since 1 is not prime.
  aesop

def LoopInvariant (seq : List Nat) (c2 c3 c5 : Nat) : Prop :=
  IsUglySeq seq ∧
  c2 < seq.length ∧ c3 < seq.length ∧ c5 < seq.length ∧
  (∀ k, k < c2 → seq[k]! * 2 ≤ seq.getLastD 0) ∧
  (∀ k, k < c3 → seq[k]! * 3 ≤ seq.getLastD 0) ∧
  (∀ k, k < c5 → seq[k]! * 5 ≤ seq.getLastD 0) ∧
  seq[c2]! * 2 > seq.getLastD 0 ∧
  seq[c3]! * 3 > seq.getLastD 0 ∧
  seq[c5]! * 5 > seq.getLastD 0

theorem LoopInvariant_next_gt_last (seq : List Nat) (c2 c3 c5 : Nat)
    (h_inv : LoopInvariant seq c2 c3 c5) :
    (nextUgly seq c2 c3 c5).1 > seq.getLastD 0 := by
  -- By definition of `nextUgly`, the next element is the minimum of `seq[c2]! * 2`, `seq[c3]! * 3`, and `seq[c5]! * 5`.
  have h_next_def : (nextUgly seq c2 c3 c5).1 = min (seq[c2]! * 2) (min (seq[c3]! * 3) (seq[c5]! * 5)) := by
    exact?;
  -- By definition of `LoopInvariant`, we know that `seq[c2]! * 2 > seq.getLastD 0`, `seq[c3]! * 3 > seq.getLastD 0`, and `seq[c5]! * 5 > seq.getLastD 0`.
  have h_next_gt_last : seq[c2]! * 2 > seq.getLastD 0 ∧ seq[c3]! * 3 > seq.getLastD 0 ∧ seq[c5]! * 5 > seq.getLastD 0 := by
    -- By definition of `LoopInvariant`, we know that `seq[c2]! * 2 > seq.getLastD 0`, `seq[c3]! * 3 > seq.getLastD 0`, and `seq[c5]! * 5 > seq.getLastD 0` follow directly from the last three parts of the conjunction.
    apply And.intro (h_inv.2.2.2.2.2.2.2.1) (And.intro (h_inv.2.2.2.2.2.2.2.2.1) (h_inv.2.2.2.2.2.2.2.2.2));
  cases seq <;> aesop

theorem IsUgly_nextUgly (seq : List Nat) (c2 c3 c5 : Nat)
    (h_inv : LoopInvariant seq c2 c3 c5) :
    IsUgly (nextUgly seq c2 c3 c5).1 := by
  -- By definition of `IsUgly`, we know that if `seq[c2]!` is ugly, then `seq[c2]! * 2` is also ugly. Similarly for `seq[c3]! * 3` and `seq[c5]! * 5`.
  have h_next_ugly : IsUgly (seq[c2]! * 2) ∧ IsUgly (seq[c3]! * 3) ∧ IsUgly (seq[c5]! * 5) := by
    have h_next_ugly : IsUgly (seq[c2]!) ∧ IsUgly (seq[c3]!) ∧ IsUgly (seq[c5]!) := by
      -- By definition of `IsUglySeq`, we know that every element in `seq` is ugly.
      have h_ugly_seq : ∀ x ∈ seq, IsUgly x := by
        -- By definition of `IsUglySeq`, every element in `seq` is ugly.
        apply h_inv.left.right.right.left;
      cases h_inv ; aesop;
    exact ⟨ IsUgly_mul_2 h_next_ugly.1, IsUgly_mul_3 h_next_ugly.2.1, IsUgly_mul_5 h_next_ugly.2.2 ⟩;
  -- Since the minimum of a set of ugly numbers is also ugly, we can conclude that `nextUgly` is ugly.
  have h_min_ugly : ∀ (a b c : ℕ), IsUgly a → IsUgly b → IsUgly c → IsUgly (min a (min b c)) := by
    grind;
  exact h_min_ugly _ _ _ h_next_ugly.1 h_next_ugly.2.1 h_next_ugly.2.2

theorem Sorted_append_of_Sorted_and_gt_last (l : List Nat) (x : Nat)
    (h_sorted : l.Sorted (· < ·)) (h_gt : x > l.getLastD 0) :
    (l ++ [x]).Sorted (· < ·) := by
  -- Since $l$ is sorted and $x > l.getLastD 0$, all elements in $l$ are less than $x$. Therefore, $l ++ [x]$ is sorted.
  have h_all_lt_x : ∀ y ∈ l, y < x := by
    -- By induction on the list l, we can show that all elements are less than x.
    induction' l with y l ih;
    · grind;
    · simp +zetaDelta at *;
      grind;
  -- Since $l$ is sorted and $x > l.getLastD 0$, all elements in $l$ are less than $x$. Therefore, $l ++ [x]$ is sorted by the properties of sorted lists.
  apply List.pairwise_append.mpr;
  -- Since $l$ is sorted and $x > l.getLastD 0$, all elements in $l$ are less than $x$. Therefore, $l ++ [x]$ is sorted by the properties of sorted lists and the fact that $x$ is greater than all elements in $l$.
  simp [h_sorted, h_all_lt_x];
  exact ⟨ h_sorted, h_all_lt_x ⟩

theorem IsUgly_decomposition {u : Nat} (hu : IsUgly u) (h_gt_1 : u > 1) :
    ∃ u' p, IsUgly u' ∧ (p = 2 ∨ p = 3 ∨ p = 5) ∧ u = u' * p ∧ u' < u := by
  -- Since $u$ is greater than 1, it must have a prime factor $p$ that is 2, 3, or 5.
  obtain ⟨p, hp⟩ : ∃ p, Nat.Prime p ∧ p ∣ u ∧ (p = 2 ∨ p = 3 ∨ p = 5) := by
    -- By definition of IsUgly, since u > 1, u must have at least one prime factor from the set {2, 3, 5}.
    obtain ⟨p, hp⟩ : ∃ p, Nat.Prime p ∧ p ∣ u := by
      -- Since $u > 1$, it must have at least one prime factor.
      apply Nat.exists_prime_and_dvd; exact h_gt_1.ne';
    have := hu.2 p hp.1 hp.2; aesop;
  obtain ⟨ u', rfl ⟩ := hp.2.1;
  refine' ⟨ u', p, _, hp.2.2, mul_comm _ _, _ ⟩;
  · exact ⟨ Nat.pos_of_ne_zero ( by aesop_cat ), fun q hq hq' => hu.2 q hq ( dvd_mul_of_dvd_right hq' _ ) ⟩;
  · nlinarith [ hp.1.two_le ]

theorem IsUglySeq_contains_one (l : List Nat) (h : IsUglySeq l) : 1 ∈ l := by
  -- By definition of IsUglySeq, l must contain all ugly numbers less than its last element, and since 1 is the smallest ugly number, it must be in l.
  have h_one_in_l : 1 ∈ l := by
    have h_first : l ≠ [] := by
      -- By definition of IsUglySeq, l ≠ [].
      apply h.2.1
    -- Since 1 is the smallest ugly number and l is non-empty, 1 must be the first element of l.
    have h_one_in_l : 1 ∈ l := by
      have h_first : l ≠ [] := h_first
      have h_ugly : IsUgly 1 := by
        exact?
      have h_one_in_l : ∀ {l : List ℕ}, IsUglySeq l → 1 ∈ l := by
        intros l hl; obtain ⟨ hl_sorted, hl_nonempty, hl_ugly, hl_all ⟩ := hl; exact (by
        rcases l with ( _ | ⟨ x, _ | ⟨ y, l ⟩ ⟩ ) <;> simp_all +decide;
        · exact Eq.symm ( le_antisymm ( le_of_not_gt fun h => by linarith [ hl_all 1 h_ugly h ] ) ( Nat.pos_of_ne_zero hl_ugly.1.ne' ) );
        · grind);
      exact h_one_in_l h;
    exact h_one_in_l;
  -- Since 1 is in l by hypothesis, we can conclude the proof.
  exact h_one_in_l

theorem candidate_ge_next (seq : List Nat) (c2 c3 c5 : Nat)
    (h_inv : LoopInvariant seq c2 c3 c5)
    (k : Nat) (hk : k < seq.length)
    (p : Nat) (hp : p = 2 ∨ p = 3 ∨ p = 5)
    (h_gt : seq[k]! * p > seq.getLastD 0) :
    seq[k]! * p >= (nextUgly seq c2 c3 c5).1 := by
  -- By definition of `nextUgly`, we know that `nextUgly seq c2 c3 c5` is the minimum of `seq[c2]! * 2`, `seq[c3]! * 3`, and `seq[c5]! * 5`.
  have h_next_def : (nextUgly seq c2 c3 c5).1 = min (seq[c2]! * 2) (min (seq[c3]! * 3) (seq[c5]! * 5)) := by
    rfl;
  rcases h_inv with ⟨ h₁, h₂, h₃, h₄, h₅, h₆, h₇, h₈ ⟩;
  rcases hp with ( rfl | rfl | rfl ) <;> simp_all +decide;
  · contrapose! h₅;
    use k;
    -- Since $k < c2$ and $seq[k] < seq[c2]$, we have $k < c2$.
    have h_k_lt_c2 : k < c2 := by
      have h_sorted : seq.Sorted (· < ·) := by
        exact h₁.1;
      have := List.pairwise_iff_get.mp h_sorted;
      exact lt_of_not_ge fun h => h₅.1.not_le <| le_of_lt <| this ⟨ c2, h₂ ⟩ ⟨ k, hk ⟩ <| lt_of_le_of_ne h <| Ne.symm <| by aesop;
    grind;
  · contrapose! h₆;
    use k;
    -- Since $k$ is a valid index, we can use the fact that $seq[k]?.getD 0$ is just $seq[k]$.
    have h_k_lt_c3 : k < c3 := by
      have := h₁.1;
      have := List.pairwise_iff_get.mp this;
      exact lt_of_not_ge fun h => h₆.2.1.not_le <| le_of_lt <| this ⟨ c3, by linarith ⟩ ⟨ k, by linarith ⟩ <| lt_of_le_of_ne h <| Ne.symm <| by aesop;
    grind;
  · contrapose! h_gt;
    convert h₇ k ( Nat.lt_of_not_ge fun h => by linarith [ show seq[k] ≥ seq[c5] from by
                                                            have := List.pairwise_iff_get.mp h₁.1;
                                                            exact monotone_iff_forall_lt.mpr ( fun i j hij => le_of_lt ( this i j hij ) ) ( show c5 ≤ k from h ) ] ) using 1;
    grind

theorem next_is_next_ugly (seq : List Nat) (c2 c3 c5 : Nat)
    (h_inv : LoopInvariant seq c2 c3 c5) :
    let next := (nextUgly seq c2 c3 c5).1
    ∀ u, IsUgly u → u < next → u ∈ seq := by
  intro next u hu hu_lt_next
  by_cases hu_gt_last : u > seq.getLastD 0;
  · -- Let `u` be the *smallest* such ugly number (i.e., `u > seq.getLastD 0`, `u < next`, and `u` is ugly).
    obtain ⟨u', hu'_min, hu'_lt_next, hu'_gt_last, hu'_in_seq⟩ : ∃ u', IsUgly u' ∧ u' < next ∧ u' > seq.getLastD 0 ∧ ∀ v, IsUgly v → v < next → v > seq.getLastD 0 → u' ≤ v := by
      exact ⟨ Nat.find ( ⟨ u, hu, hu_lt_next, hu_gt_last ⟩ : ∃ u', IsUgly u' ∧ u' < next ∧ u' > seq.getLastD 0 ), Nat.find_spec ( ⟨ u, hu, hu_lt_next, hu_gt_last ⟩ : ∃ u', IsUgly u' ∧ u' < next ∧ u' > seq.getLastD 0 ) |>.1, Nat.find_spec ( ⟨ u, hu, hu_lt_next, hu_gt_last ⟩ : ∃ u', IsUgly u' ∧ u' < next ∧ u' > seq.getLastD 0 ) |>.2.1, Nat.find_spec ( ⟨ u, hu, hu_lt_next, hu_gt_last ⟩ : ∃ u', IsUgly u' ∧ u' < next ∧ u' > seq.getLastD 0 ) |>.2.2, fun v hv hv_lt_next hv_gt_last => Nat.find_min' _ ⟨ hv, hv_lt_next, hv_gt_last ⟩ ⟩;
    -- By `IsUgly_decomposition`, `u' = u'' * p` where `u''` is ugly, `u'' < u'`, and `p ∈ {2, 3, 5}`.
    obtain ⟨u'', p, hu''_min, hp, hu'_eq⟩ : ∃ u'' p, IsUgly u'' ∧ (p = 2 ∨ p = 3 ∨ p = 5) ∧ u' = u'' * p ∧ u'' < u' := by
      by_cases hu'_gt_1 : u' > 1;
      · exact?;
      · interval_cases u' <;> simp_all +decide [ IsUgly ];
        have := h_inv.1.1; simp_all +decide [ List.Sorted ] ;
        rcases seq with ( _ | ⟨ x, _ | ⟨ y, seq ⟩ ⟩ ) <;> simp_all +decide [ List.getLast? ];
        · cases h_inv ; aesop;
        · cases h_inv.1.2.2.1 0 ( by norm_num ) ; aesop;
        · have := h_inv.1.2.2.1 0; simp_all +decide ;
          grind;
    -- Since `u''` is ugly and `u'' ≤ seq.getLastD 0`, by `h_inv`, `u'' ∈ seq`.
    have hu''_in_seq : u'' ∈ seq := by
      have := h_inv.1.2.2.2;
      grind;
    -- Let `k` be the index of `u''` in `seq`. Then `u' = seq[k]! * p`.
    obtain ⟨k, hk⟩ : ∃ k, k < seq.length ∧ seq[k]! = u'' := by
      obtain ⟨ k, hk ⟩ := List.mem_iff_get.mp hu''_in_seq; use k; aesop;
    -- Since `u' = seq[k]! * p` and `u' > seq.getLastD 0`, we can apply `candidate_ge_next` to `seq[k]! * p`.
    have hu'_ge_next : seq[k]! * p ≥ next := by
      apply candidate_ge_next seq c2 c3 c5 h_inv k hk.left p hp;
      grind;
    grind;
  · have h_seq_gt_u : seq.Sorted (· < ·) ∧ seq ≠ [] ∧ (∀ x ∈ seq, IsUgly x) ∧ (∀ y, IsUgly y → y < seq.getLastD 0 → y ∈ seq) := by
      exact h_inv.1;
    have h_seq_gt_u : ∀ {l : List ℕ}, List.Sorted (· < ·) l → l ≠ [] → (∀ x ∈ l, IsUgly x) → (∀ y, IsUgly y → y < l.getLastD 0 → y ∈ l) → ∀ y, IsUgly y → y ≤ l.getLastD 0 → y ∈ l := by
      intros l hl_sorted hl_nonempty hl_ugly hl_lt_last y hy hy_le_last
      induction' l with x l ih generalizing y;
      · contradiction;
      · grind;
    grind

theorem LoopInvariant_step (seq : List Nat) (c2 c3 c5 : Nat)
    (h_inv : LoopInvariant seq c2 c3 c5) :
    let (next, c2', c3', c5') := nextUgly seq c2 c3 c5
    LoopInvariant (seq ++ [next]) c2' c3' c5' := by
  -- Show that the new sequence and indices satisfy the loop invariant.
  simp [LoopInvariant] at *;
  refine' ⟨ _, _, _, _, _ ⟩;
  · refine' ⟨ _, _, _, _ ⟩;
    · have h_sorted : (nextUgly seq c2 c3 c5).1 > seq.getLastD 0 := by
        -- Since the minimum of the three products is greater than the last element, the next element must be greater than the last element.
        have h_next_gt_last : (nextUgly seq c2 c3 c5).1 = min (seq[c2]! * 2) (min (seq[c3]! * 3) (seq[c5]! * 5)) := by
          exact?;
        grind;
      have h_sorted : List.Sorted (· < ·) seq := by
        exact h_inv.1.1;
      exact?;
    · aesop;
    · -- By definition of `nextUgly`, the next element is the minimum of `seq[c2]! * 2`, `seq[c3]! * 3`, and `seq[c5]! * 5`, all of which are ugly numbers.
      have h_next_ugly : IsUgly (nextUgly seq c2 c3 c5).1 := by
        apply IsUgly_nextUgly;
        -- By definition of `LoopInvariant`, we need to show that the sequence is sorted, non-empty, contains only ugly numbers, and includes all ugly numbers less than the last element.
        apply And.intro h_inv.left;
        grind;
      simp +zetaDelta at *;
      rintro x ( hx | rfl ) <;> [ exact h_inv.1.2.2.1 x hx; exact h_next_ugly ];
    · -- By definition of `nextUgly`, we know that `(nextUgly seq c2 c3 c5).1` is the smallest ugly number greater than `seq.getLastD 0`.
      have h_next_ugly : ∀ y, IsUgly y → y < (nextUgly seq c2 c3 c5).1 → y ∈ seq := by
        apply next_is_next_ugly;
        -- By definition of `LoopInvariant`, we need to show that the sequence is sorted, non-empty, contains only ugly numbers, and includes all ugly numbers less than the last element.
        apply And.intro h_inv.left;
        grind;
      grind;
  · -- Since $c2 < \text{length}(seq)$, adding 1 to $c2$ gives $c2' < \text{length}(seq) + 1$.
    have h_c2'_lt : (nextUgly seq c2 c3 c5).2.1 ≤ c2 + 1 := by
      unfold nextUgly; aesop;
    linarith;
  · -- Since $c3 < seq.length$, adding 1 to $c3$ will still be less than $seq.length + 1$. Therefore, $(nextUgly seq c2 c3 c5).2.2.1 < seq.length + 1$.
    have h_c3_lt : (nextUgly seq c2 c3 c5).2.2.1 ≤ c3 + 1 := by
      unfold nextUgly; aesop;
    linarith;
  · simp [nextUgly];
    grind;
  · unfold nextUgly;
    simp +zetaDelta at *;
    refine' ⟨ _, _, _ ⟩;
    · intro k hk; split_ifs at hk <;> simp_all +decide [ List.getElem?_append ] ;
      · grind;
      · grind;
    · grind;
    · refine' ⟨ _, _, _ ⟩;
      · grind;
      · split_ifs <;> simp_all +decide [ List.getElem_append ];
        · -- Since the list is sorted, we have seq[c2] < seq[c2+1] when c2+1 < seq.length.
          by_cases h_case : c2 + 1 < seq.length;
          · have := h_inv.1.1;
            replace := List.pairwise_iff_get.mp this;
            exact Or.inl ( by simpa [ h_case ] using this ⟨ c2, by linarith ⟩ ⟨ c2 + 1, by linarith ⟩ ( Nat.lt_succ_self _ ) );
          · grind;
        · grind;
      · constructor <;> split_ifs <;> simp_all +decide [ List.getElem_append ];
        · split_ifs <;> simp_all +decide [ min_eq_iff ];
          · have := h_inv.1.1;
            have := List.pairwise_iff_get.mp this;
            exact Or.inr <| Or.inl <| this ⟨ c3, by linarith ⟩ ⟨ c3 + 1, by linarith ⟩ <| Nat.lt_succ_self _;
          · grind;
        · grind;
        · split_ifs <;> simp_all +decide [ Nat.mul_succ ];
          · have := h_inv.1.1;
            have := List.pairwise_iff_get.mp this;
            exact Or.inr <| Or.inr <| this ⟨ c5, by linarith ⟩ ⟨ c5 + 1, by linarith ⟩ <| Nat.lt_succ_self _;
          · grind;
        · grind

theorem LoopInvariant_base : LoopInvariant [1] 0 0 0 := by
  -- Show that [1] is a sorted list of ugly numbers.
  simp [LoopInvariant, IsUglySeq];
  -- Since 1 is positive and has no prime factors, it is an ugly number.
  have h1 : IsUgly 1 := by
    -- By definition, 1 is an ugly number.
    apply IsUgly_one
  exact ⟨h1, by intro y hy hy0; exact absurd hy0 (by exact Nat.ne_of_gt (hy.left))⟩

theorem IsUglySeq_implies_nth_ugly (l : List Nat) (h : IsUglySeq l) :
    ((List.range (l.getLastD 0)).filter (fun i => isUgly i)).length = l.length - 1 := by
  -- By definition of `IsUglySeq`, we know that `l` contains exactly the first `l.length` ugly numbers.
  have h_seq : List.toFinset (List.filter (fun i => isUgly i) (List.range (l.getLastD 0))) = List.toFinset (List.dropLast l) := by
    ext xop;
    norm_num +zetaDelta at *;
    constructor;
    · intro hxop
      have h_mem : xop ∈ List.filter (fun i => isUgly i) (List.range (l.getLastD 0)) := by
        rw [ List.mem_filter ] ; aesop;
      have h_mem : xop ∈ l := by
        have h_mem : ∀ y, IsUgly y → y < l.getLastD 0 → y ∈ l := by
          exact h.2.2.2;
        rw [ isUgly_iff_IsUgly ] at hxop ; aesop;
      rw [ List.mem_iff_get ] at *;
      obtain ⟨ n, hn ⟩ := ‹∃ n : Fin l.length, l.get n = xop›; use ⟨ n, by
        grind ⟩ ; aesop;
    · intro hxop;
      -- Since `l` is sorted and contains only ugly numbers, any element in `l.dropLast` must be less than the last element of `l`.
      have h_lt_last : xop < l.getLastD 0 := by
        have h_lt_last : ∀ {l : List ℕ}, List.Sorted (· < ·) l → ∀ x ∈ l.dropLast, x < l.getLastD 0 := by
          -- We can prove this by induction on the list.
          intro l hl x hx
          induction' l with a l ih generalizing x;
          · contradiction;
          · -- If x is in the dropLast of a :: l, then x is either in l.dropLast or x is a.
            by_cases hx_l : x ∈ l.dropLast;
            · cases l <;> aesop;
            · rcases l with ( _ | ⟨ b, l ⟩ ) <;> simp_all +decide [ List.getLastD ];
              induction l using List.reverseRecOn <;> aesop;
        exact h_lt_last h.1 xop hxop;
      exact ⟨ by simpa using h_lt_last, by simpa using isUgly_iff_IsUgly xop |>.2 ( h.2.2.1 xop <| List.mem_of_mem_dropLast hxop ) ⟩;
  rw [ ← List.toFinset_card_of_nodup, h_seq, List.toFinset_card_of_nodup ];
  · exact?;
  · exact h.1.nodup.sublist ( List.dropLast_sublist _ );
  · refine' List.Nodup.filter _ _;
    exact?

#check nthUglyNumber.loop

theorem LoopInvariant_loop (i : Nat) (seq : List Nat) (c2 c3 c5 : Nat)
    (h_inv : LoopInvariant seq c2 c3 c5) :
    ∃ c2' c3' c5', LoopInvariant (nthUglyNumber.loop i seq c2 c3 c5) c2' c3' c5' ∧
    (nthUglyNumber.loop i seq c2 c3 c5).length = seq.length + i := by
  -- By definition of `nthUglyNumber.loop`, we can apply the invariant step by step.
  induction' i with i ih generalizing seq c2 c3 c5;
  · exact ⟨ c2, c3, c5, h_inv, rfl ⟩;
  · -- By definition of `nthUglyNumber.loop`, we can apply the induction hypothesis to the result of `nextUgly` and the updated counters.
    obtain ⟨c2', c3', c5', h_inv', h_len⟩ := ih (seq ++ [(nextUgly seq c2 c3 c5).1]) (if (nextUgly seq c2 c3 c5).1 = seq[c2]! * 2 then c2 + 1 else c2) (if (nextUgly seq c2 c3 c5).1 = seq[c3]! * 3 then c3 + 1 else c3) (if (nextUgly seq c2 c3 c5).1 = seq[c5]! * 5 then c5 + 1 else c5) (LoopInvariant_step seq c2 c3 c5 h_inv);
    -- By definition of `nthUglyNumber.loop`, we can rewrite the goal in terms of the loop function and apply the induction hypothesis.
    simp [nthUglyNumber.loop];
    -- By definition of `nthUglyNumber.loop`, we can rewrite the goal in terms of the loop function and apply the induction hypothesis to conclude the proof.
    apply And.intro;
    · exact ⟨ _, _, _, by simpa [ nextUgly ] using h_inv' ⟩;
    · convert h_len using 1 ; simp +arith +decide [ add_comm, add_left_comm, add_assoc ]

theorem nthUglyNumber_spec_satisfied (n: Nat) (h_precond : nthUglyNumber_precond (n)) :
    nthUglyNumber_postcond (n) (nthUglyNumber (n) h_precond) h_precond := by
  -- By `LoopInvariant_loop`, there exist `c2', c3', c5'` such that `LoopInvariant seq c2' c3' c5'` holds, and `seq.length = 1 + (n - 1) = n`.
  obtain ⟨c2', c3', c5', h_inv, h_len⟩ : ∃ c2' c3' c5', LoopInvariant (nthUglyNumber.loop (n - 1) [1] 0 0 0) c2' c3' c5' ∧ (nthUglyNumber.loop (n - 1) [1] 0 0 0).length = 1 + (n - 1) := by
    have := LoopInvariant_loop ( n - 1 ) [ 1 ] 0 0 0 LoopInvariant_base; aesop;
  -- Since `seq.length = n`, `seq[(n - 1)]!` is the last element of `seq`.
  have h_last : (nthUglyNumber.loop (n - 1) [1] 0 0 0)[(n - 1)]! = (nthUglyNumber.loop (n - 1) [1] 0 0 0).getLastD 0 := by
    grind;
  -- From `h_inv`, we know `IsUglySeq seq`.
  have h_ugly_seq : IsUglySeq (nthUglyNumber.loop (n - 1) [1] 0 0 0) := by
    exact h_inv.1;
  -- This implies all elements of `seq` are ugly, so `isUgly (seq[(n - 1)]!) = true`.
  have h_ugly : isUgly ((nthUglyNumber.loop (n - 1) [1] 0 0 0).getLastD 0) = true := by
    convert h_ugly_seq.2.2.1 _ _;
    convert isUgly_iff_IsUgly _;
    grind;
  -- Also, `IsUglySeq_implies_nth_ugly` tells us that the number of ugly numbers less than `seq.getLastD 0` is `seq.length - 1`.
  have h_count : ((List.range ((nthUglyNumber.loop (n - 1) [1] 0 0 0).getLastD 0)).filter (fun i => isUgly i)).length = (nthUglyNumber.loop (n - 1) [1] 0 0 0).length - 1 := by
    apply IsUglySeq_implies_nth_ugly; assumption;
  unfold nthUglyNumber; aesop;
